### ISSUE TITLE
Add `xo` to submodule

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#119]
@guillaumevincent  What do you think about adding `xo` to the submodule so it's a condition to merge PR? (as in lesspass/cli#2)

**Comment by guillaumevincent** [comment]
I think it a waste of time, does it brings some value to our users ?

If people spend some time doing some tests instead of implementing eslint, check and valid what rules they want, add comment in their code to avoid specific rules, etc.

linter are good for big teams to get a certain consistency in the code. But for us it's a waste of time.
