### ISSUE TITLE
Mobile app security issue

### ISSUE THREAD

**Issue by keshto** [lesspass/lesspass#157]
We should have an accessibility service (bitwarden) or keyboard (keepass) to fill in user/pass as copy and paste is a known security issue.

**Comment by guillaumevincent** [comment]
Hi @keshto,

do you have more information about the copy and paste security issue?

Does this issue related to https://github.com/lesspass/lesspass/issues/50 ?

**Comment by keshto** [comment]
here is the paper http://fc13.ifca.ai/proc/4-2.pdf

**Comment by guillaumevincent** [comment]
@keshto it seems that MyLessPass use `android.content.ClipboardManager` https://github.com/Syject/MyLessPass-Android/blob/ed1b84341d2f639eaff0972349121255c9445f36/domain/src/main/java/com/syject/domain/utils/SystemUtils.java#L4

What are your recommendation to copy generated password?

Because I don't understand:

1. if this is a security issue, why MyLessPass implement it?
2. the white paper says: _all apps use the clipboard feature to transfer credentials from the password_
3. if there is a malicious app installed on your device, your are compromised anyway


>Based on the lack of API support for third-party password managers on the
Android OS, developers decided to opt for the best usability they could achieve
by including the clipboard feature to allow users to copy-and-paste usernames
and passwords from their apps to other apps. Although all but one developer
were aware of the possible security threat, they decided that better usability
was more important than stronger security.

I will close this one, after adding a note on known risk on the wiki

I saw the USecPassBoard workflow in the white paper but it seems over complicated.

**Comment by guillaumevincent** [comment]
close this one

Note added to the wiki https://github.com/lesspass/lesspass/wiki#security-issues

**Comment by fxnn** [comment]
If I understand you correctly, you comprise security for user friendliness. To me, when talking about a password app, which is meant to improve security in the first place, that's a very questionable decision.

Especially, your third argument is fatal. Security always arises from a combination of measures. Nothing bad will happen when a malicious app is installed on my device, because that's what permissions and isolation are made for. And that's why Apps should take care not to disclose secret information without at least allowing the user to make an informed decision.

In the end, user friendly alternatives do exist and are in use. Apps like LastPass and 1Password support form autofill. And e.g. KeePassDX and LastPass do provide a keyboard, which, by the way, can easily be switched to with two taps.

To me, LessPass is a great idea, but it provides no user friendly and secure way to transfer the password into another app. Using the clipboard is not secure, and typing it manually is not user friendly.

**Comment by guillaumevincent** [comment]
Lastpass form autofill was the cause of the biggest flaws in the application.

Security is always a compromise between security and usability.

We can create an issue to find a secure way to transfer generated password from LessPass to another app.

**Comment by fxnn** [comment]
Thank you for your answer, and sorry, I was unclear about the autofill point. I didn't refer to web autofill, where websites captured data using hidden fields, but to Android autofill, which to my knowledge [can be used in a secure way](https://www.xda-developers.com/password-manager-autofill-api-data-leak/) to transfer passwords, and is even meant to do so.

Would this be, from your point of view, an option worth evaluating in a separate issue?

**Comment by guillaumevincent** [comment]
Yes I not against improving the security of LessPass if we don't loose to much usability.

Feel free to create an issue for this one
Cheers
