### ISSUE TITLE
How to continue after hitting the "default"-button?

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#161]
When I am changing the default settings on https://lesspass.com/
and afterwards hit the "gear-wheel" symbol to reset to default options
this is what happens:

![1](https://cloud.githubusercontent.com/assets/20812775/23502157/1332393a-ff37-11e6-9bd5-2578633292d9.gif)

So the settings are back to default - but how am I supposed to proceed?
There is only the login-field accessible now.

**Comment by guillaumevincent** [comment]
@panther2 nice feedback

This is a page where you can modify default options used by the application.
So you hit default option, then modify the options, it modify the default options and save it locally.

For you, when you hit default options button, it should save existing password profile as default?

**Comment by panther2** [comment]
I seem to have it misunderstood. I thought it was a reset button to revert to the original settings.

So the procedure is intended to be as follows:

1. Browse to https://lesspass.com/
2. Hit the default options button.
3. Modify the options to the desired values
... but then? 

I am still stuck to the window illustrated above... what is to be intered to be entered into "Login".
How is anything saved (and where? Is it a cookie?

Maybe Ihave missed a documentation of this feature? In this case please point me to it.

Thank you :-)

**Comment by guillaumevincent** [comment]
There is no documentation, and it's a good feedback because our app should not need documentation. If not, it's because it's not good enough.

> what is to be entered into "Login"? Login to what?

For example, if you use always your email as login, you can enter your email here. Every time you open the app, it will auto fill login with this option.

> How is anything saved and where? Is it a cookie?
Local storage (directly in your browser)

>Is it (the password profile) saved site-wise and/or login-wise or is it valid for all passwords to be created?
sorry I didn't understand

>Is it linked to the "connected mode"?
no, but there is an option to save default options into LessPass Database https://github.com/lesspass/lesspass/issues/71

**Comment by panther2** [comment]
I am starting to understand this feature. ;-)

So it is not only the settings that may be saved as default but the login information, too. Indeed, saving the login would only be reasonable in case it is identical on most sites.

>> Is it (the password profile) saved site-wise and/or login-wise or is it valid for all passwords to be created?
>sorry I didn't understand

As I did not understand the "login field" before, I wondered about the purpose of this login field.
I did not know if it addressed the login-field required on a special site, or a login for a special purpose (for example connected mode) or for all passwords to be created.

I have now understood that this feature serves as storing a pattern for creating all (or at least many) of the users passwords - including the (hopefully identical on many sites) login information. 

I will try out now if this works as now expected on my Chrome browser...

**Comment by panther2** [comment]
@guillaumevincent 
I am still running into problems, I am afraid:

See 
![1](https://cloud.githubusercontent.com/assets/20812775/23512605/7abda682-ff61-11e6-8e18-0a52ba02dc55.gif)

Please note that the inserted login name is not saved correctly. Also when getting back to lesspass.com the information that I wanted to be saved has not been taken over.

Here

![2](https://cloud.githubusercontent.com/assets/20812775/23512689/bf63d13a-ff61-11e6-98ad-93d8c98d2d76.gif)

the inserted login name is incorrectly saved, too. But now the other information sored has been taken over correctly.

The difference between the first and the second video is:
- In the first video I entered lesspass com via my bookmark that is saved as https://lesspass.com/#
- In the second video I entered lesspass com via entering https://lesspass.com

So apart from the login name issue the user might run into problems depending on how the app is accessed.

**Comment by guillaumevincent** [comment]
@panther2 yeah this is a bug, https://github.com/lesspass/lesspass/issues/162
Don't understand why.

Strange bookmark, did you accidentally remove the trailing `/` in `https://lesspass.com/#/`

We will improve this page, maybe with a popup "Do you want to save those options as default?" when you click on default options.

Can we close this issue and open an enhancement one?

**Comment by panther2** [comment]
No, I did not remove the `/`

Yes, I am closing this in favour of #162 

Thank you.

**Comment by guillaumevincent** [comment]
No thank you to you :)
It was a great feedback with some useful gifs!

**Comment by edouard-lopez** [comment]
@guillaumevincent,
The default preset screen seems more confusing than in previous version (with `save default` button on the options section). 

In this version the form his lacking context and guidance. Instead of the alert block on top of the form a `set as default` button will provide such guidance and explicit the action accomplished. While autosave is cool it make you feel like you have lost some control.
We are in a different situation than google docs auto-saving document, we want to **voluntarily set a default preset**.

Anyway, this form as standalone was confusing for me and I knew the feature. I reckon it's better to revert back to previous mechanism (at the bottom of main form). 

---

When visiting the default option screen:

* [ ] login value is changed when an option is toggled (as shown in @panther2 GIF)
  * seems the value is restored to a previous state.
