### ISSUE TITLE
Strange behaviour on default options

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#162]
On default options page, when we click on an option, the login field if replace by his first letter:

![demo](https://cloud.githubusercontent.com/assets/20812775/23512689/bf63d13a-ff61-11e6-98ad-93d8c98d2d76.gif)

**Comment by edouard-lopez** [comment]
@guillaumevincent,
The default preset screen seems more confusing than in previous version (with `save default` button on the options section). 

In this version the form his lacking context and guidance. Instead of the alert block on top of the form a `set as default` button will provide such guidance and explicit the action accomplished. While autosave is cool it make you feel like you have lost some control.
We are in a different situation than google docs auto-saving document, we want to **voluntarily set a default preset**.

Anyway, this form as standalone was confusing for me and I knew the feature. I reckon it's better to revert back to previous mechanism (at the bottom of main form). 

---

When visiting the default option screen:

* [ ] login value is changed when an option is toggled (as shown in @panther2 GIF)
  * seems the value is restored to a previous state.
