### ISSUE TITLE
[Pure - offline standalone version] Bad URL is copied

### ISSUE THREAD

**Issue by Kcchouette** [lesspass/lesspass#179]
I'm using pure as it's described here: https://github.com/lesspass/lesspass/issues/68#issuecomment-260071145

But when I copied the URL (from the share/copied button), the URL looks like: `https://lesspass.com/#/?login=&site=aaaa&uppercase=true&lowercase=true&numbers=true&symbols=true&length=16&counter=1&version=2` instead of `file:///C:/[FOLDER]/lesspass-pure/index.html#/?login=&site=aaaa&uppercase=true&lowercase=true&numbers=true&symbols=true&length=16&counter=1&version=2`

Can you fix that please?

**Comment by guillaumevincent** [comment]
yes we can try to use http host instead of baseURL

**Comment by guillaumevincent** [comment]
@Kcchouette the share button is a way to "share" your password with somebody.
How can someone can use your local file `file:///C:/[FOLDER]/lesspass-pure/index.html` ?

**Comment by Kcchouette** [comment]
Oh, it was a way to "share" my password. I was using it as an alternative to #154 :(

So I don't really know

**Comment by edouard-lopez** [comment]
I'm closing this as it was due to a misunderstanding.

@Kcchouette it's a way to share the profile (not the password itself). If you mean to use this feature as a way to export your password, maybe you should have a look at the [connected mode](https://github.com/lesspass/lesspass/wiki/Private-vs.-connected-mode)
