### ISSUE TITLE
Prefix and suffix option

### ISSUE THREAD

**Issue by kidburglar** [lesspass/lesspass#189]
Hello, sorry to make another ticket.
But I'm not sure you receive my answer on #181 after you closed it.

You didn't answer about the suffix / prefix that will be choose by the user and only replace / add to the generate password.

Cheers.

**Comment by guillaumevincent** [comment]
@kidburglar what problem do you try to solve? 

Actually LessPass return at least one char in every characters set:
https://github.com/lesspass/core/blob/master/tests/v2/renderPassword.tests.js#L38-L69

What you can't control is the number of char in every characters set.
We are not going to add a prefix or a suffix because:

 * this feature will be useful for a very small amount of sites.
 * this will add complexity in the interface

For those sites, you will need to add the prefix manually

Do you have an example of site with those stupid rules?

**Comment by kidburglar** [comment]
Ah I didn't know that LessPass took at minimum 1 char for each characters set.
In this case it's ok, I close this issue.
Thanks for your answer.
