### ISSUE TITLE
Add icon in the context menu

### ISSUE THREAD

**Issue by kidburglar** [lesspass/lesspass#195]
Hello,
It's more a feature for usability but some website open a new window without adding the add-on icons.

It would be nice to have a right click option for this kind of website to avoid copying the URL in another window and copy paste the password.

Cheers.

**Comment by panther2** [comment]
@kidburglar 
Can you please provide an example of such a website - maybe I better understand your idea then.
Thank you :smiley:

**Comment by kidburglar** [comment]
Yes but not sure it will not really help ^^
I had the case at chrono.gg

I bought the game and I had a window of paypal but withtou all my add-on icons.

**Comment by panther2** [comment]
@kidburglar 
I will try to take a look...
What do you mean by "add-on" icon? The icon of the extension?
And what exactly do you want to right-click then?

**Comment by kidburglar** [comment]
The icons that you have next to the address bar in Firefox like lesspass, ublock origin...
In the right click I think that a button that display a lesspass window would be nice, but I don't know if it's possible.

**Comment by Kcchouette** [comment]
The pop-up that @kidburglar speaks seems to be like that: http://js.do/code/145735 (click on the result panel on "link to pop-up")
So in this pop-up we don't have any link to the lesspass add-on.

I think @kidburglar want that in the right click context menu we have a shortcut to open the lesspass add-on without switching windows.

**Comment by guillaumevincent** [comment]
Same @panther2 I don't understand the workflow. 
You go on example.org, click on the login button, and it opens a popup without menu bar.

You want to right click in the popup, click LessPass in the context menu to open the web extension? I don't think browser allow web extension to appear in pop up.

What about:
`ALT+TAB` > `CTRL+SHIFT+L` > fill form and copy password > `ALT+TAB` > `CTRL+V`

instead of:
`right clic open LessPass` > fill form and copy password > `ALT+TAB` > `CTRL+V`

Ok you are going to do one more action but you don't mix mouse and keyboard. So it will be faster

**Comment by kidburglar** [comment]
@guillaumevincent 
More action is not a problem if the shortkey are describe somewhere it's ok for me.
(same if I find alt+tab > ctrl+shift+l a little long)

**Comment by guillaumevincent** [comment]
@kidburglar so 
`ALT+TAB` + left click on the icon

I close this one, because [contextMenus](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/contextMenus) in web extension force us to injects JavaScript into every web pages user visit.

This is something we don't want: see https://github.com/lesspass/lesspass/wiki/FAQ#why-there-is-no-auto-fill-feature-in-the-web-extension

**Comment by kidburglar** [comment]
@guillaumevincent 
Little precision.
When I do ctrl + shift + l I see like lesspass try to display but not work on the popup.
It's not possible to make it display some if the icon is not in the window ?

**Comment by guillaumevincent** [comment]
no you have to `ALT+TAB` before to come back to your main window
