### ISSUE TITLE
LessPass Core evolution

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#224]
Hello community.

I initiated a radical change in LessPass Core. LessPass uses encryption methods: [pbkdf2](https://nodejs.org/api/crypto.html#crypto_crypto_pbkdf2_password_salt_iterations_keylen_digest_callback) with 100k iterations for password generation and [hmac-sha256](https://nodejs.org/api/crypto.html#crypto_class_hmac) for master password fingerprint.
The code is in node and uses the object `Buffer` and the native module [crypto](https://nodejs.org/api/crypto.html). `Buffer` object does not exist in your browser. To run LessPass in your browser we use Browserify which transforms `Buffer`, `crypto.pbkdf2` and `crypto.createHmac` into a version compatible with your browser.

To perform 100k iterations in your browser, LessPass core first try to uses webcrypto (JavaScript API for performing basic cryptographic operations in web applications. See [draft](https://w3c.github.io/webcrypto/Overview.html)).
All other implementations are not fast enough (even [Stanford Javascript Crypto Library](http://bitwiseshiftleft.github.io/sjcl/)).
Generating on a browser that does not have webcrypto take a few second (~2s on Safari iOS iPhone 6).

This morning I tried to build a full version of LessPass core without `Buffer` nor the `crypto` node module. For `pbkdf2` and `createHmac` I created two versions. A node version (with the use of `crypto` and `Buffer`) and a browser version with [Unibabel](https://git.daplie.com/Daplie/unibabel-js/) and webcrypto.

browser field in `package.json` used by Browserify

```
"browser": {
    "./src/pbkdf2.js": "./src/pbkdf2.browser.js",
    "./src/hmac.js": "./src/hmac.browser.js"
}
```

[source code](https://github.com/lesspass/core/tree/master/src)

![screenshot from 2017-05-13 19-53-31](https://cloud.githubusercontent.com/assets/943762/26027874/34056aca-3816-11e7-8f10-87bf0217bdec.png)

it works well! 👍  I'm trying to see if there is no regression.

 * the first gain is the reduction of the module size. 80% reduction, the core module is now only 9ko gziped.
 * I have to do tests to see if it does not solve a problem with react-native (@nachoaIvarez feel free to send me feedback on this one).
 * there is still a problem to solve, webcrypto doesn't works on Safari mobile and IE11, and it's broken on Edge. Now I think using a polyfill for IE11, Edge and Safari on iOS.

Another interesting point, LessPass core is tested with Firefox, Chrome and Node and uses the same tests for the 3 test suites [see](https://travis-ci.org/lesspass/core)

If you want to try the next version: `npm install lesspass@next`

Best!

**Comment by Kcchouette** [comment]
About this evolution, is the generated version the same than the v2?
At first view, the encryption method is the same than the v2, and the hash too, so this evolution doesn't change the password of the v2, does it?

**Comment by guillaumevincent** [comment]
@Kcchouette the API is identical and yes the generated passwords are the same.

**Comment by nachoaIvarez** [comment]
Thanks for this awesome refactor, 80% sounds awesome! 🎉 

## Regarding React Native:
Unibabel thinks React Native is a node context. The thing is that Unibabel infers that only because it is not a browser context (!browser => node), which is obviously a false assumption (funny error message though: `[Unibabel] You are doing it wrong` 😂). By locally tweaking a bit both unibabel and lesspass core (bypassing Unibabel env check and forcing lesspass use the non-node approach), I found out that approach will not work because there's not such thing as window.crypto in React Native context. So, keeping the shimed-node-modules approach seems like the only way to go currently. That said, I'm thinking another alternative, which is having a either a [webworker](https://github.com/devfd/react-native-workers) in which I hope `window.crypto` exists, or as a last resort, an embeded [WebView](https://facebook.github.io/react-native/docs/webview.html#onmessage) with no UI only to perform the password calculation as it is a browser context.

**Comment by guillaumevincent** [comment]
@nachoaIvarez maybe another solution is to bind native function and inject inside LessPass core

related: https://github.com/lesspass/lesspass/issues/223
