### ISSUE TITLE
LessPass at RMLL

### ISSUE THREAD

**Issue by panther2** [lesspass/lesspass#241]
@guillaumevincent 
@edouard-lopez 

I have just downloaded and studied your today's presentation of LessPass at the RMLL!

( https://prog2017.rmll.info/programme/securite-entre-transparence-et-opacite/lesspass-gestionnaire-de-mot-de-passe-open-source?lang=en )

So great that you were given the chance to demonstrate the project there. Congrats! 
And congrats for a well structured and interesting presentation.

So what was the audience like and what feedback did you get?

I would like to take this event as a chance to thank you both for such a great tool, and also for giving the community the chance to be a part of it!

**Comment by guillaumevincent** [comment]
Hello @panther2,

RMLL was really great, we got some interesting feedback on our product. RMLL will post the video of our presentation soon.

Basically the 2 mains features people are asking for are: 

 * Use yubikey to get/fill the master password
 * Public password profiles (remove completely the need of LessPass Database)

We will discuss with the community about this, because we don't know the implementation yet.

We also presented the first version of LessPass Move. We are missing some features: but here is the demo: https://lesspass.github.io/move/

We talked about the security aspect of LessPass with some cryptographers and analyze different threat models.

So there is more to come in the next weeks. We will blog about this soon.

❤️

**Comment by panther2** [comment]
That sounds really good! 
Thank you for sharing.

Now I am waiting for the video :smile:

**Comment by panther2** [comment]
Closed now, as this served communication purposes insted of being a real "issue" :smile:

**Comment by guillaumevincent** [comment]
@panther2 here is the video https://rmll.ubicast.tv/videos/demo-04-07-2017-092046_55603_part334_66469/

**Comment by panther2** [comment]
Thanks a lot!
