### ISSUE TITLE
Redesign of lesspass.com (In Progress)

### ISSUE THREAD

**Issue by ElectricCookie** [lesspass/lesspass#249]
Hey there!
I'm loving LessPass more and more and I would love to give back, maybe you actually like it.

This is a new hero design for the front-page. I made it quite a bit more bold and moved the LessPass "form" out. I think it might be overwhelming at first. I'm thinking about an introduction first that can be disabled to jump straight to the form once you're a regular user. 

I also think the benefits should be highlighted even more, which is why I moved them up to the top. 

The image is from unsplash.com and therefore not licensed.

I'm still unsure about the color of the logo and navigation bar.. Any suggestions? 

![Hero Design](http://i.imgur.com/SkiHo8f.jpg)

Would love to hear your feedback!

**Comment by guillaumevincent** [comment]
Amazing :)

My first suggestion:

 * Logo in blue (#3398eb) because it's hard to see
 * Button in blue (#3398eb) ?
 * LessPass is the first stateless password manager > We are not the "first". We are the "most popular" or the "most used"

If you want you can create a github page with your code, we can iterate on this one. I will be happy to replace the actual site by this one, when it will be ready.

**Comment by ElectricCookie** [comment]
Thanks a lot for the feedback! I will change the colors. I will have some illustrations ready in a few days. I also have some design ideas for the UI as well... 

I think I will just update this issue with further progress before starting the code.

**Comment by edouard-lopez** [comment]
That's a great initiative, thanks !

I like the fact the presence of a phone and a laptop suggest the cross-platform.

### Hero

The _be smart about password_ flatter user ego - hehe
 
> Don't store password - encrypt them.

We are not encypting pwd, it's a derivation/generation but we need a bette wording.

### Features

Text should be case consistent (either in title case or lower case).

* **button**
    > Get **S**tarted
* **features**
    > Stat**e** of the art **c**ryptography

    We are using PBKDF2, which is a standard, not a bleeding edge (it will be `scrypt` or better). 

  > ~No passwords leave your computer~ → Password stay on your computer

  > ~No syncing needed~ → On all devices without syncing

  > privacy by default_ (heard at the RMLL 2017)

  > can remember stupid rules

**Comment by guillaumevincent** [comment]
@edouard-lopez We will discuss after to improve the wording. Because for `On all devices without syncing` and `can remember stupid rules` the sentences are not clear.

> the form must stay on the pass

Maybe not, because we should encourage people to use web extension. 
IMO the form should go under the fold.

@ElectricCookie Avoids the tunnel effect. It's always better to make a first version on a github page. This will help us to help you and give you feedback early. You can use https://fakeimg.pl/ for example. Don't spend to much on wording. We are better together. And the best will occurs after many iterations.

Best

**Comment by ElectricCookie** [comment]
How about a compromise between the two opinions.. I like the idea of a low barrier to entry - so why not make a minimal version of the ui directly under the hero. Would look like this:

```INPUT FIELD (site) | INPUT FIELD (login) | INPUT FIELD(master) |  BUTTON(big blue, Generate) ```
Text below: For more options and security switch to the full web-app / extension

**Comment by edouard-lopez** [comment]
@guillaumevincent form below the fold is ok, I meant to keep it on the homepage.  

@ElectricCookie the form is actually the same component as the one in the extensions so different layout would require extra CSS

**Comment by guillaumevincent** [comment]
Hello @ElectricCookie, any update on this?
Do you have any repository we can work on?
How can I help?
Thank you

**Comment by ElectricCookie** [comment]
Hey @guillaumevincent, 
work has recently been very busy. I haven't forgotten this. I will give you an update soon. I haven't set up something yet tho. If you want to you can already bootstrap something!

**Comment by guillaumevincent** [comment]
Hello @ElectricCookie 
I close this one.
Thank you for your start on a redesign. 
Feel free to reopen this issue when you will have a repo bootstrapped somewhere.
❤️
