### ISSUE TITLE
Add Android app to F-Droid so users without Google Apps can install it

### ISSUE THREAD

**Issue by ABrambleNinja** [lesspass/lesspass#252]
This app probably attracts many privacy minded individuals, many of whom might use an Android device that does not have Google's proprietary GApps installed (Maps, Gmail, Chrome, Play Store, etc). Those users must compile this application from source, which can be time consuming/tedious. Instead, F-Droid is an alternative to the Play Store that is open source and allows only open source applications to be submitted. I could look into getting it submitted for you, but I don't have much experience with developing for Android.

**Comment by guillaumevincent** [comment]
Hello @ABrambleNinja,
@Rudloff open an issue for this one on fdroid 3 months ago https://gitlab.com/fdroid/rfp/issues/82
fdroid seems a little dead since the departure of the creator.

I don't have some time to spend on this, could you ask some update on fdroid forum if the subject interest you.

duplicates https://github.com/lesspass/lesspass/issues/177
