### ISSUE TITLE
Lesspass safari extension?

### ISSUE THREAD

**Issue by danydacosta** [lesspass/lesspass#264]
Hello,

Is a Lesspass safari extension planned? I would love to use it on Safari.

**Comment by guillaumevincent** [comment]
Hello @danydacosta,
for now we can't because of webcrypto implementation on Safari and Apple Developer Program
See: https://github.com/lesspass/lesspass/issues/126
If we spend 99$ per year for Apple Developer Program (https://github.com/lesspass/lesspass/issues/261) we will see at this time if Safari do a better job with web crypto
