### ISSUE TITLE
Implement support for saving multiple profiles for a single website

### ISSUE THREAD

**Issue by pieter3457** [lesspass/lesspass#279]
I would like to see the possibility to save profiles with different usernames but the same site name at the same time, instead of overwriting the existing profile when saving a new profile with a different username but same site name.

For example, if I have two accounts for google.com, test1@gmail.com and test2@gmail.com.
If I save the one with username test1@gmail.com first,
then save the profile with test2@gmail.com, only the profile with test2@gmail.com would be saved, because the profile with test1@gmail.com would be overwritten.

It would be better if perhaps a dialog window would pop up, asking if the user would want to overwrite the existing profile or add a new one.

When logging in, I think it would be especially nice to see a drop down with usernames saved for the current site, if there are multiple usernames saved for the site.

**Comment by guillaumevincent** [comment]
> If I save the one with username test1@gmail.com first,
then save the profile with test2@gmail.com, only the profile with test2@gmail.com would be saved, because the profile with test1@gmail.com would be overwritten.

This is a bug 🐛 
You need to click on LessPass title between the two save.
I will fix that

> When logging in, I think it would be especially nice to see a drop down with usernames saved for the current site, if there are multiple usernames saved for the site.

After this bug fixed, you already get a dropdown in the site field:

![test](https://user-images.githubusercontent.com/943762/31013831-36bd7f5e-a518-11e7-9888-ae44eeeb4e4c.png)
