### ISSUE TITLE
integration into web forms, fill in on web

### ISSUE THREAD

**Issue by jeroen7s** [lesspass/lesspass#290]
using the masterpassword and the login you put in to username field, you could calculate the password and automatically fill in the fields in the browser, preferably this would be well-integrated into the web form, so you don't have to open the extension, type your username twice (once in lesspass, once in the form) and makes the experience much more streamlined, also lesspass could auto-suggest usernames previously saved in the extension directly into the forms

**Comment by guillaumevincent** [comment]
Hello @jeroen7s,
most of the hack on password manager's web extensions are possible because of auto-fill feature.
See FAQ: https://github.com/lesspass/lesspass/wiki/FAQ#why-there-is-no-auto-fill-feature-in-the-web-extension
If companies like Lastpass with brilliant engineers cannot properly protect their extensions, I think we should avoid adding attack vectors.
