### ISSUE TITLE
Trigger autocomplete of previously entered values in <input>s

### ISSUE THREAD

**Issue by DavidBruant** [lesspass/lesspass#3]
Browser inputs have native autocomplete. They're not used by the app. They'd make the UX better.

**Comment by edouard-lopez** [comment]
I took notice of that, but need to investigate though.
The HTML seems correct to me, it might be a `vue.js` issue.

**Comment by edouard-lopez** [comment]
I've a hunch, as we never submit the form the input are probably never store by the browser. We need to find some documentation and discuss the impact of adding this behaviour on security and user experience.

* **pros**
  * that's the expected behavior (hence this issue) ;
  * prevent input errors, by suggesting already typed values to user ;
  * fasten form completion, so reduce workflow disruption.
* **cons**:
  * reduce security as browser will prompt to store password in its password manager (which is counter-productive) ;
  * increase surface attack as `who` and `where` would be freely accessible and only password will require engineering.

**Comment by DavidBruant** [comment]
> reduce security as browser will prompt to store password in its password manager (which is counter-productive) ;
> increase surface attack as who and where would be freely accessible and only password will require engineering.

What's your threat model? Is the user browser at risk?

**Comment by guillaumevincent** [comment]
@DavidBruant  I've try to fix this issue by submitting the form, and it works pretty well. The only problem I encounter now is the browser auto save login functionality.
I don't want to save anywhere the master password.

So I need a to create an `input` with password behaviour without `type=password` field.

**Comment by DavidBruant** [comment]
[@autocomplete="new-password"](https://html.spec.whatwg.org/multipage/forms.html#attr-fe-autocomplete-new-password). See https://youtu.be/MnvUlGFb3GQ?t=249
I don't know browser support status.

**Comment by edouard-lopez** [comment]
See [Form example](https://www.chromium.org/developers/design-documents/form-styles-that-chromium-understands):
```
<form id="login" action="signup.php" method="post">
  <input type="text" autocomplete="username">
  <input type="password" autocomplete="new-password">
  <input type="submit" value="Sign Up!">
</form>
```

Or:

```
<form id="login" action="signup.php" method="post">
  <input type="text" autocomplete="username">
  <input type="password" autocomplete="new-password">
  <input type="password" autocomplete="new-password">
  <input type="submit" value="Sign Up!">
</form>
```

**Comment by guillaumevincent** [comment]
> Browsers will still offer to remember login and password.

 [How to Turn Off Form Autocompletion](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion)

If we submit the form, browsers will always prompt to save login and password. So because I don't want to save the master password for LessPass, I prefer not to submit the form.

`@autocomplete="new-password"` doesn't seems to works (ie @edouard-lopez jsfiddle)

In the new version, I allow autocomplete for site field, and use datalist. 
You will be able to save password info in a LessPass database. IMO this will solve partially this problem.

I close
