### ISSUE TITLE
Provide docker-compose.yml for using with an existing reverse proxy

### ISSUE THREAD

**Issue by husimo** [lesspass/lesspass#304]
Hello,
First of all, thank you for that wonderful software !
Right now it's good because it works out of the box but if you have anything else on your server it's not working.
Would it be possible to provide a docker-compose.yml for using it with an existing reverse proxy ?

1. Not generate any let's encrypt certificate.
2. Do not need to provide any domain name for nginx container.
3. Not use "ports" for nginx container but "expose".
4. Allow nginx container to be used only with HTTP (no redirection to HTTPS)

Thank you

**Comment by guillaumevincent** [comment]
Hello @husimo,
I'm not sure I understand properly, it looks like you want to install LessPass on an existing server.
So the only thing you need is to create another http container that fit your need.
This container is dependent on your configuration.

You can probably start using https://github.com/lesspass/lesspass/blob/master/docker-compose.prod.yml and replace nginx container with yours.

I do not like the idea of providing a container without HTTPS. It could be used as easier to install, but it would not make LessPass users more secure.

LessPass Database need port 443 open for LetsEncrypts

I close this issue because I do not think it's a good idea. I'll let you answer here. If you want help to create the http container that fits your needs, do not hesitate to open another issue with your code if you are blocked.
