### ISSUE TITLE
Publish entropy-java on maven

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#308]
Hello,
If you're familiar with Maven, Java and you know how to push a library easily on Maven, I do want some help to push [entropy-java](https://github.com/lesspass/entropy-java).
I need it in the [LessPass React Native app](https://github.com/lesspass/mobile).

If you have good tutorials, do not hesitate to post them here.
Thank you

**Comment by mevatron** [comment]
@guillaumevincent At where I work we've used Sonatype's Nexus, which now has a Dockerized setup here: https://github.com/sonatype/docker-nexus

Also, since you're an open-source project you may be able to apply for JFrog's Artifactory, which I believe can also be setup as a Maven repo: https://jfrog.com/open-source/

Hope those are helpful ideas, and cool project by the way!

**Comment by guillaumevincent** [comment]
Thanks @mevatron 
I will look at JFrog's Artifactory this week

**Comment by guillaumevincent** [comment]
Hello,
I've published the repo to JCenter: https://bintray.com/lesspass/entropy-java
I'm waiting for the approval of Bintray
