### ISSUE TITLE
Pictograms change again after delay

### ISSUE THREAD

**Issue by SystemParadox** [lesspass/lesspass#312]
Hi. I am a little confused by pictograms on the lesspass interface.

Firstly, I don't know what to call these - are these mentioned in any documentation anywhere?

I assume these are some sort of hash to aid users in noticing if they typed the password incorrectly. Every time I type a character into the master password box they change. What I don't understand is why they change again after about second?

Also, why does clicking on the pictograms reveal the master password? That seems a bit hazardous to me, it's definitely not what I was expecting.

Thanks.

**Comment by edouard-lopez** [comment]
Hello,
You're right, the icons are here to help detect and correct typos on the master password. I will add wiki page.

We call this the _**icons fingerprint**_, you can find the history of this UI element in [icon fingerprint - Helping hash depend on Master Password only](https://github.com/lesspass/lesspass/issues/10).

The randomness of icon when you type is a feature to prevent information leak when we computed the hash on each new character (see #48). The debounce you see at the end is due to aforementioned issue and the time it takes to compute the real hash.

Revealing the Master password when you click the fingerprint is a feature not a bug, when you have a long passphrase edit it is faster than re-typing the whole thing.

Could you elaborate on what you where expecting?

**Comment by SystemParadox** [comment]
Thanks, that answers my question.

Regarding revealing the password, I would expect to reveal it with a "reveal password" button. I was just playing around clicking on the icons fingerprint and suddenly became aware that my password was visible for all to see!
