### ISSUE TITLE
what do you think about LessPass remoteStorage

### ISSUE THREAD

**Issue by GammaNu** [lesspass/lesspass#313]
https://lesspass.alhur.es/

**Comment by edouard-lopez** [comment]
It's always nice to see community-build project.

However, having _lesspass_ and _remote storage_ in the same sentence trigger a red flag with me, so does the lack of any tests.

There is [security reasons to go against autofill feature](https://github.com/lesspass/lesspass/wiki/FAQ#why-there-is-no-auto-fill-feature-in-the-web-extension), that's why we don't have one.

**Comment by edouard-lopez** [comment]
My bad, [remoteStorage](https://remotestorage.io/) seems to be an interesting way to decouple access to your personal data from the app.

**Comment by edouard-lopez** [comment]
@fiatjaf You might want to weight in?

**Comment by fiatjaf** [comment]
Me? I like it a lot, it is very good!

Just kidding. Why do you think autofill is bad in this particular way I'm doing it? (Indeed, it is not "autofill" as people understand it, right? That would involve saving the passwords and writing them to pages without explicit user commands. My approach is much more simple than that, just a thin addition to the official LessPass extension.)

As for [remoteStorage](https://remotestorage.io/), I think it is a usable alternative to LessPass "connected version" or whatever (I've never used that, actually), indeed much more in line with the LessPass ideal of having no single central point of failure. I don't know why do you think it is bad.

**Comment by edouard-lopez** [comment]
Ping @guillaumevincent For reference, the [filling script](https://github.com/fiatjaf/lesspass-remotestorage/blob/master/thin-content-script.js).

@fiatjaf I think the remoteStorage is interesting but need more explanation on your readme/page. Could you elaborate on how your fill-field feature work relative to the [2nd point in the FAQ](https://github.com/lesspass/lesspass/wiki/FAQ#why-there-is-no-auto-fill-feature-in-the-web-extension)?

**Comment by fiatjaf** [comment]
remoteStorage is a protocol. People have to know about it before they start using it, because they must sign up for a remoteStorage server or run their own. My extension will not send people's data to anywhere they didn't authorize explicitly.

The script is only injected when you click in the browserAction or the contextMenu item.

**Comment by guillaumevincent** [comment]
Yes there is an open issue about remoteStorage

https://github.com/lesspass/lesspass/issues/91

I will take a look at it soon.
Thank you @fiatjaf

**Comment by pwFoo** [comment]
I'm new with remoteStorage (and lesspass) but it sounds good to me. 
Maybe it would be nice to have docker images and a compose file to setup lesspass with self hosted remoteStorage? Is there an example to do it?

**Comment by guillaumevincent** [comment]
I close this one, we can continue the discussion on #91 
I love the idea behind remote storage protocol. There are 2 main issues, I don't have a lot of time actually to engage myself in a backend rewrite. And there is not a lot of remote storage implementation. So people will still continue to use the one I will add.

But I keep #91 open, because I like the idea.
Thank you @fiatjaf
