### ISSUE TITLE
'Password must be less than 35' breaks existing passwords

### ISSUE THREAD

**Issue by VannTen** [lesspass/lesspass#322]
Hi there.

I am a happy user of lesspass, and I usually set the length of my generated password to 50, unless the site itself require less.
But today, the Chrome expansion no longer allows that. And so I have lost all access to my generated passwords :/
Is there a way to allow at least an option to set the maximum over 35 ? What is the benefit of that change ?
(I am aware that over a certain value (35, i guess), the reste is just padding, but what is wrong with that to disallow it ?)

Thank you, and another thank you for that great tool ;).

**Comment by guillaumevincent** [comment]
Hello @VannTen,
the password generated length cannot be more than 35 because of the size of the entropy consumed. See https://github.com/lesspass/lesspass/wiki/Generated-password-info. It didn't change anything regarding the password length. 

 > And so I have lost all access to my generated passwords :/

Are you talking about LessPass connected and the saved password profiles? I didn't change anything. It should work.

> (I am aware that over a certain value (35, i guess), the reste is just padding, but what is wrong with that to disallow it ?)

Did you update your browser?
Because the last time the [options changes](https://github.com/lesspass/pure/blob/6a0ddfa887877ae7079b7d50ac7ada76cbec1368/src/components/Options.vue) was 5 months ago.

Can you do some new tests on your side?

**Comment by VannTen** [comment]
I understand that having a generated password does add anything ; however, does it harm ?
Previously, all my generated password (besides a few exceptions for sites which didn't allow it) were 50-characters long. Having mistakenly paste  them in the url field sometimes, i saw that in the end was only `a` characters. So, as far as I understand, beyond 35 characters, lesspass was adding padding characters to the password. And that, although it does not add entropy, does not prevent it either, am I correct ?

> Are you talking about LessPass connected and the saved password profiles? I didn't change anything. It should work.

No, I mean, since I can no longer generate password of 50 characters, my passwords being 50-characters, i can not generate them with lesspass anymore.

> Did you update your browser?
Because the last time the options changes was 5 months ago.

I haven't updated my browser specifically, but it might have beem (the first time I experienced that was on one of my school's computer.
 I forgot to mention : I had this issue on Chrome(64.0.3282.119), on Mac OS (10.12.6) (school computer) Lesspass version (3.1.1), and Chromium(I havent the specific version just now), on Ubuntu (17.10)(mine). I have used lesspass on both before with 50-characters password without a problem, around a week ago (maybe a little more).

I also just tried on Firefox, and find the same limitations.


Would there be a way for me to somehow tweak the extension code directly in my browser in order to allow myself to generate a password without that limit, as a temporary workaround ?

Thank you for your time.

**Comment by guillaumevincent** [comment]
Hello @VannTen,
I understand your problem, it's just that I didn't understand why you didn't have the limitation before.

**As a temp workaround** you can try to install a [previous version](https://github.com/lesspass/webextension/releases). Unzip the source code and 'load unpacked extension' in your browser extension panel.

> I understand that having a generated password does add anything ; however, does it harm ?

The length of the generated password does not matter in the security of LessPass.
A password generated from 30 characters is as secure as a password of 10 or 50.
The attack vector of LessPass is that you have to know the generated password to try to find the master password. If you know the generated password, you also know its length.

Does it harm? yes because it gives a semblance of security. The length field is here for site with stupid password rules. It's not here to make the generated password more secure.

**Comment by guillaumevincent** [comment]
I will try to find why the issue appears recently.

Another workarounds:

 * install the previous version on Firefox https://addons.mozilla.org/en-US/firefox/addon/lesspass/versions/?page=1#version-3.0.3
 * `npm install --global lesspass-cli` then `lesspass site login -L=50`

**Comment by guillaumevincent** [comment]
The patch which introduce the limitation: https://github.com/lesspass/pure/commit/aa6c82f8c99c60b89b77f286ac4e7f186b014650#diff-4e80f5a32e189769daf6a979bb1dffa6

client side validation for a form in HTML5 is triggered only when form is submitted :disappointed:
