### ISSUE TITLE
 Would you like to respond to my concerns?

### ISSUE THREAD

**Issue by schorsch3000** [lesspass/lesspass#34]
Hi, I see a few possible (security) issue with this system.
Would you like to respond to my concerns?
# Security

I could make a webservice that provides some service for free so alot of customers would sign up.
I would store Passwords in plain text.
Some of these customers may use lesspass.
Now i could filter out obvious non-random passwords.
After that i may bruteforce masterpasswords with lesspass and prove that against customer passwords.
By having the masterpassword i can generate all passwords for that given user.
# convenience

Am i supposed to remember the password-generation setting for each service on each login?
Some services deny some characters for passwords. There is an option for that, but do i really have to remember that an every login?

Some Services have quite specific requirements to a password, like 8 to 10 chars (my bank) how does that work?

My employer uses the AD credentials for a lot of services, there a different webservices under differen domain names, all using the same username and password, how does that fit in?

My employer enforces a new password every 3 month, how does that fit?

My employer enforces a password to be at least 8 characters long, has lower and upper letters numbers and one of the following chars: !"+-*%=?, no other special char how does that fit?

**Comment by guillaumevincent** [comment]
Hi @schorsch3000, 
we have answered many of your questions in this [post](https://github.com/lesspass/backend/blob/b4f557ddd5b502d7f7370e327ed3efe1b520ffbf/Dockerfile).

## Security 

If I understand well, someone create a site to obtain a password for this site let's say : **otAN7%ocIX7,**. This will be very expensive, or it will take some time to break that password via brutus force. If someone is willing to spend so much money to find your master password, then it is that you are too important to use LessPass. 
If someone targeted you, it will probably find a simpler way to hack you : 

![security](https://imgs.xkcd.com/comics/security.png)

So my advice, use a strong master password (more than 20 chars). You can use space, unicode char.

And we are working on a way to help user to change their master password.

## Convenience
Sometimes some sites have specific password rules. For instance, some banks only accept passwords with numbers. So you have to remember both a strong password and the its complex rules.

Well, we built a “connected” version to tackle that. It works by saving your password’s profile, i.e. everything**except the master password and the generated passwor** to be able to generate the password. Then, next time you need this password you just have to select the profile and type the master password.

![LessPass_Database](https://cdn-images-1.medium.com/max/800/1*O-Fxo_s7vlHGqL3vfKSl-Q.gif)

If you have any question please feel free to ask on this ticket,

**Comment by edouard-lopez** [comment]
Hi @schorsch3000,
1. Did you try the app ? 
1. Would you mind create one issue per question next time ? 

### Security

Brute forcing won't be as simple with only a generated password:

1. we use [PBKDF2](https://www.wikiwand.com/en/PBKDF2) to raise the cost of breaking master passwords ;
1. you will need to know the `site` and `login` which **can be anything** ;
1. you will need need to know the options used (`length`, `counter`, etc.) ;

And again, you will have similar hurdles once you get the master password: find `site`/`login`/`options`.

But you are right, LessPass is no silver bullet and as every system it's breachable. So our goal is two folds: **① make it hard to break  ② easier to use**.  

### Convenience

* remembering password: you can [use the _connected version_](https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4#ffbc) ;
* specific requirements to a password: answer connected version might help ;
* AD credentials: you will use LessPass to generate your AD password, they use similar options when you need to. As changing the `site`, `login` and `options` quickly became tedious you can use the autocomplete feature of the connected version to fill the info for you.
* new password every 3 month: change the `counter` value
* super convoluted rules (_!"+-*%=?, no other special char_): this case is not [better talk about entropy](https://www.explainxkcd.com/wiki/index.php/936:_Password_Strength) to the security guy or change company :P

**Comment by guillaumevincent** [comment]
@schorsch3000 I close
Feel free to open a new issue if you have another question, or continue on this thread

**Comment by Jormund** [comment]
This thread didn't convince me that master passwords can't be bruteforced. I am not a security/cryptography expert and would love to be wrong.
PBKDF2 is used to raise the cost of password generation. But lesspass is "not that slow" running in JS and browsers. If I apply the same algorith using a lower level language and environnement, I can run it faster (let's say a .exe in C/C#/Java).
If you host your own service as described and know a user's password and login, you can try bruteforce using the default options. The site field is probably using this format: https://lesspass.com
(since the site field is also used by lesspass app and extensions to match the visited page)

If you have all the information & fast calculation, it looks like bruteforce will do the trick ?
Or did I miss something ? is the slowness of PBKDF2 not dependent of software and infrastructure ?

**Comment by guillaumevincent** [comment]
If you have a password profile, and the generated password, yes you can try to brute force the master password.

Depending on the entropy of the master password it will take a long time.
And depending on the hardware you use, it will also take some time.

A strong master password is 60 bits of entropy.
An infeasible to guess master password is 128 bits of entropy (see https://security.stackexchange.com/questions/6141/amount-of-simple-operations-that-is-safely-out-of-reach-for-all-humanity)

> This thread didn't convince me that master passwords can't be bruteforced

A master password can be brute forced!
This is not the important part. What's important is how much does it cost?

Security is like protecting your bike. If someone has decided to steal your bike, you can use the best antitheft device on the market, if the thief comes with a tractor then he can steal your bike.
To be safe, stealing your bike costs more than stealing your neighbor's bike. And that reselling the bike pays more than the money spent stealing your bike (having a hydraulic clamp).

So you should think twice if you plan to protect your 1000 bitcoins with LessPass password.

> If you host your own service as described and know a user's password and login, you can try bruteforce using the default options. 

In term of security, we should always talk about threat models.
So if your threat model for you is: LessPass Database host trying to stole your master password, then you can self host your LessPass Database or use LessPass offline and never save your password profiles.

Does that make sense?

**Comment by Jormund** [comment]
128 bits is infeasible right now. You'll say I can just change your password every year to keep up with technology, but with lesspass it's a very long task because it changes every generated password.

I don't worry much about lesspass database, I don't think my own setup is more secure than lesspass.com. (I don't have any rational reason to blindly trust lesspass.com, but I don't have a valid reason either to think I can do better security than people with experience in the field)
I was more thinking about the fact that most users will use default options when presented with a choice. And thus default password profile is a safe bet for an attacker.
But obviously, I myself can just follow your advice and use custom profile and will be safer than my neighbor.

So my understanding of your answer is defining a very high entropy master password and using custom password profiles are best practices with lesspass. 
But I haven't seen this advice on lesspass.com. I know enough on the subject to not have a trivial password but I worry about less "tech-savvy" users. Those best practices are sort of "required" if lesspass wants to protect 100% of it's users. The neighbor being more vulnerable is an individual solution, not a collective one.
That's a problem I have encountered searching for password managers. None of them explain the security, how it should be used properly and why it is better than the other. It's like you need to be security expert to choose and use a password manager. But the reality is you don't need to be a security expert to have 200 online accounts and needing different passwords (and needing a password manager...)
Tel me if I'm wrong, but I think a poorly configurated security solution is not very much of a security solution.

**Comment by guillaumevincent** [comment]
I take care not to give too many advices on security. It's a dangerous field. My advice is the following: understand how you password manager works, understand threat models and decided to use it or not.

My advice : use a strong master password. Keep your master password in your head and use the web extension. Keep default options because sometimes usability is a trade off with security.

Why: 

It will be better than using the same password on every site (threat model: database leak). LessPass provide one password different per site. :+1:

You don't need to sync anything (threat model: LessPass Database got hacked, emails and profiles leak. Hackers try to link emails with another site leak and brute force weak master password) mitigation> strong master password

Threat model: complex man in the middle modifying https://LessPass.com and inject malicious JavaScript. Use web extension or mobile app.

Threat model: your password manager contains malicious code > use an open source one. Look at the code or ask some friend to do some audit.

If the threat model someone targeting you and will try to spend thousands and thousands of dollars to brute force your master password. Then use another password manager > keepass with physical key.

**Comment by polarathene** [comment]
> 128 bits is infeasible right now.

128 bits is a very big number. If you were to brute-force all possible numbers in that range, at a rate of 1 guess per second, this is how many years it would take:

`2^128 / (60*60*24*365*10^15) = 10790283070806014`

After the `365`, we are multiplying this by `10^15`, that is 1,000,000,000,000,000 years to divide by. Yet still we have 10,790,283,070,806,014 as our answer. That's over 10x that amount of years multiplied by that already large amount of years. So even if instead of 1 password guess per second, you had hardware that could guess `10^15` times per second, it's still impossible to exhaust every possibility in a lifetime.

`log10(2^128 / (60*60*24*365)) = ~31` may be a better way to present that number to you. That's a 1 followed with 31 zeros after it for years at one guess per second.

Presently a SHA-256 hash can be guessed at a rate of about 7 billion per second with a modern GPU like the nvidia RTX 3080. That's a mere `7 * 10^9`. Passwords themselves generally go through a process to further increase the computation difficulty to slow down attacks further. LessPass uses PBKDF2 with 100,000 (`10^5`) iterations, that is it's doing the SHA-256 computation 100k times. The attacker must do that for each guess. The expensive GPU is now only managing 70k guesses per second instead of 7 billion.

The attacker would need to spend a lot of money, time and electricity to be successful, assuming the master password really is 128-bits of entropy (random generation, not predictable/biased choice like "This is my really secure password!"). They will instead find more affordable means to get your password from you if they want it, as has been explained above.

---

**TL;DR:** 128-bits of entropy for password strength is very secure and will remain so. Most passwords users enter are rarely that strong.

Easiest way to remember them is to generate a 10 word long passphrase using something like EFF diceware generator. That will randomly choose from 7776 possible words and give you the 128-bits of entropy `log2(7776^10) = ~129`. You can use the math provided here to choose a "weaker" and thus shorter passphrase, but still very difficult/expensive to attack and recover the original password.

- `log2(7776^5) = ~64`, only 5 words randomly selected from the 7776 word list is still 64-bits of entropy.
- `log10(2^64 / (60*60*24*365)) = ~11.7` More than 100 billion years.
- Against the 3080 GPU when considering 70k/sec rate due to SHA-256 PBKDF2 100k iterations: `(10^11.7) / (7*10^4) = 7159817`, still over 7 billion years.
- Attacker will usually have success guessing the password after guessing 50% of the key space, half of 64-bit number is 63 bits (each bit doubles the number from a starting number of 2), 3.5 billion years.
- With 1 million times that computing power (1 million of the GPU or other advancements), it's still 3,500 years to typically be successful.

If you'd like an online generator that uses the EFF wordlist, you can find one [here](https://bitwarden.com/password-generator/) ([related code](https://github.com/bitwarden/jslib/blob/master/src/services/passwordGeneration.service.ts)).
