### ISSUE TITLE
Prevent invalid value 

### ISSUE THREAD

**Issue by edouard-lopez** [lesspass/lesspass#362]
In mobile beta `3.0.2` you can put a negative `counter` and `length`. I guess for the counter it can be a possibility yet a strange one, for the length it doesn't make sense to have it.

Current behaviour highlight the fields in red but guiding user by preventing invalid values is a better way.

![screenshot_lesspass_20181215-081546](https://user-images.githubusercontent.com/1212392/50040360-3a737f00-0042-11e9-8162-e47b9518c0f7.png)

**Comment by guillaumevincent** [comment]
On mobile an textinput numeric always return a text. It's difficult to force an integer on the fly.
If you enter 1 for example we display a red box. But maybe you are just going to type 5 for a length of 15.
Imagine the following scenario:
 * you prevent clic on + or - if data will become invalid (length = 35 and you try to clic on + button, nothing append)
 * User enter 1 in the field then decide to use the + button to reach 10. Data will become 2 so it's invalid so nothing append. 
To avoid that we should detect we are going in the good direction.

What I love with the actual system:

Scenario: you disable all the options. when you disable the last one, generate button disable and options become red. You know directly you did something wrong. For me we didn't have to display an error message. Because it's obvious that one option is mandatory.

**Comment by edouard-lopez** [comment]
I was thinking to disable the <kbd>-</kbd> (minus) button when reaching `0` or a set minimal value.

The scenario you describe when all option are disabled is nice, I didn't notice the behaviour.
