### ISSUE TITLE
Saving generated passwords for specific sites on Android

### ISSUE THREAD

**Issue by coltondrg** [lesspass/lesspass#363]
On Android devices with a fingerprint reader, the new React native version of LessPass allows storing the master password in Android's encrypted data store so the accounts can be unlocked without having to type the password, but I don't really want to do that because I have security concerns relating to Android's encrypted storage and fingerprints as a secure authentication method in the first place. 

It would be amazing if I could make LessPass remember the generated password for specific websites that I use frequently on my phone so I can access those quickly using my fingerprint without trusting my master password to it. I propose adding a fingerprint button next to the copy button after a password is generated, which will store the password, then I should be automatically prompted to use my fingerprint sensor in the future when I select that profile from the database. It would also be nice if there was some way for it to check the other values in the database to determine if the password has been changed so the user could be warned if an outdated password is stored.

**Comment by guillaumevincent** [comment]
Hello,
I will close this one.
In term of user experience I don't know if it would improve something ("fingerprint > nav > search > clic > clic" versus "search > clic > fingerprint > clic").

Also if you don't "trust" the Android's encrypted storage, then LessPass is probably not for you. I mean the security in LessPass is inferior to Keepass or Birwarden, because of the deterministic nature of the tool.

Feel free to comment if you disagree
