### ISSUE TITLE
Android: Web login process improvement suggestion

### ISSUE THREAD

**Issue by thenhustey** [lesspass/lesspass#404]
Hello, at first - thanks for a nice manager.

I have a suggestion for better usability on Android.

How I imagine filling a login form:

1. Open login page in a browser and share it to LessPass (it shares a link in plaintext)
2. LessPass uses this link to fill a domain input (maybe it could be done without leaving the browser (like adding link to Pocket)
3. Fill a login into an input on the login page and then select written text - android shows context menu (Cut, Copy, ... , LessPass). Taping on LessPass sends login into LessPass.
4. MasterPassword prompt is shown. When filled and confirmed, the login password is copied into a clipboard and LessPass is closed/hidden.
5. I'm back on the login page with password in a clipboard. Paste. Login. Done.

**Comment by edouard-lopez** [comment]
Hello @thenhustey 

If you use firefox mobile and lesspass addon you get the site autofill mechanism for free :tada:

**Comment by praxiq** [comment]
> If you use firefox mobile and lesspass addon you get the site autofill mechanism for free 🎉

Are you sure about that? The wiki clearly states that there is no autofill feature in the extension anymore: https://github.com/lesspass/lesspass/wiki/FAQ

Android Oreo has [an autofill API](https://developer.android.com/guide/topics/text/autofill) for password manager apps. Integrating that into LessPass would be wonderful, and ought to be more secure than auto-filling with a WebExtension.

**Comment by guillaumevincent** [comment]
@praxiq do you have a demo of the pocket feature you talked about?
I'm interesting about improving the workflow on android!

**Comment by guillaumevincent** [comment]
closing this one
Feel free to send us a video of the workflow you would like.
To be honest I don't understand correctly the workflow you described.

**Comment by praxiq** [comment]
I didn't suggest that Pocket workflow, that was @thenhustey. It sounds complicated to me.

I suggested instead, using Android's built-in autofill API, which is specifically designed for password apps to autofill passwords easily! If you've used an Android device in the last few years you've seen it, since it comes with Google's password manager autofill-enabled by default. [Here's a video](https://www.youtube.com/watch?v=NKyThWu3Nrc) demonstrating the feature with a third-party password manager, and showing the permission settings page where you can see he has several autofill-enabled password managers installed.
