### ISSUE TITLE
Delete account from lesspass

### ISSUE THREAD

**Issue by reyqn** [lesspass/lesspass#414]
So I just started to use lesspass and I created my account to store profiles a little too quickly.
Thing is I used my masterpassword to login (without encrypting it).
Is there any way to delete my account? Or to change my password?

Also I tried the android app, which by default encrypts the password when you login, thus the encrytped password didn't match the non-encrypted password I used to create the account, and the app just crashed on failed login.

**Comment by guillaumevincent** [comment]
Send me an email @ contact@lesspass.com with your email for an account deletion or reset your password for a password reset

**Comment by teohhanhui** [comment]
The UX around the master password / encrypted password for lesspass.com is still really bad and confusing. Using the master password directly should really not be an option, as using your master password as lesspass.com account password is a huge security risk!

What should happen:

Register:
1. User enters email and master password.
2. User clicks on Register.
3. Password is generated from master password.
4. Generated password is sent to lesspass.com

Sign In:
1. User enters email and master password.
2. User clicks on Sign In.
3. Password is generated from master password.
4. Generated password is sent to lesspass.com

So that the master password never leaves the client.

Security should not be opt-in. To support old users who used a plain password, there could be a checkbox to "use plain password".

**Comment by guillaumevincent** [comment]
@teohhanhui you are speaking about the web component or the mobile app?
Because what you describe is exactly what is on the mobile application.

The master password should never leave the client. If you use the old system you need to encrypt manually your master password by clicking on the "ecnrypt my master password", or use a plain password.

I'm rewriting the web component to be like the mobile app. Feel free to open another issue to be sure we fix this UX issue

Cheer

**Comment by guillaumevincent** [comment]
see  #420 @teohhanhui
