### ISSUE TITLE
LessPass Default Password Profiles

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#423]
> Every day, thousands of people are configuring custom rules for services they want to use. It’s time to leverage this information to improve user experience.

https://blog.lesspass.com/lesspass-default-password-profiles-99e4d01dec5

I will update the code to:

> send anonymous data to LessPass server. Restricted to the base domain name, site and the options used to generate a password. You will have the possibility to opt out. I will create and update existing policies.

I open the discussion for any feedback here

**Comment by Kcchouette** [comment]
I don't know if LessPass web is a success, it's sad to not have news about existing service LessPass occurs (even by having the number of downloads etc).

---

> send anonymous data to LessPass server

 - Here my feedback: To my mind, SaaS was a mistake. And it's a mistake.
I know that society wants more and more data about people, it's sad that even small projects want to do the same...
Yes, I know, doing data analytic with metadata ("we don't know the password but we know you are on this website") is the new mode…
But we already have had WOT (web of trust that resells data)... And we will have perenity of the project, mitm after that, etc

 - I don't know what's the strategy in a court-middle and long term, but for me, the long term would have a stable stateless password manager, building with the community.

Middle term would have to inaugurate in term of security: see https://github.com/lesspass/lesspass/issues/389 for eg; or even https://github.com/lesspass/lesspass/labels/%3Alock%3A%20security  
Long term would be modifying design so that users are happy (https://github.com/lesspass/lesspass/issues/278 https://github.com/lesspass/lesspass/issues/338 etc )

- To finish, I would prefer that you would look into solution for offering static build (but already asking here https://github.com/lesspass/lesspass/issues/191#issuecomment-291533243), or isolated offline application for lesspass (sadly `history` exists on cli, spying exists when using certificate on windows, etc), or try to use bg-free language (eg rust instead of C/C++)

Thanks for reading me.

---

Direct comment about the blog post:

> Imagine a world where you only need to enter your master password on any site to generate the appropriate password. No more options to change.

It would be the google-sphere, bad world :(
Or the [jquery one](https://github.com/lesspass/lesspass/wiki/FAQ#why-there-is-no-auto-fill-feature-in-the-web-extension)

**Comment by panther2** [comment]
> send anonymous data to LessPass server. Restricted to the base domain name, site and the options used to generate a password. You will have the possibility to opt out. I will create and update existing policies.

What about the countless use-cases where LessPass calculates passwords totally unrelated to a website?

> Imagine a world where you only need to enter your master password on any site to generate the appropriate password. No more options to change.

Honestly? That would be terrible. Again, LessPass is not limited to "(web)-sites" - personally I need its flexibility given by those options. Or maybe (as I hope) I have misunderstood the concept...

**Comment by guillaumevincent** [comment]
In term of user experience, it's bad to have to change the options to use only 6 numbers for https://ing.fr/. If you are on the ING website, you probably want to have those options selected for you.

@panther2 what is your concern regarding the password generation for non website? It won't change, you will be able to use LessPass as today. You will just have a way to select the custom rule for stupid sites in one click.

> I know that society wants more and more data about people, it's sad that even small projects want to do the same...

We need some data if we want to improve the product. I have no idea how LessPass is used. 

> But we already have had WOT (web of trust that resells data)... And we will have perenity of the project, mitm after that, etc

I remain open to discussion, what is the problem here? getting anonymous data? reselling data?
Feel free to describe your need.

> offering static build

In which form ? you have the cli completely offline. I don't understand the history problem. You want to not save the command in history (see https://stackoverflow.com/a/8473153/866886)?

**Comment by panther2** [comment]
@guillaumevincent 
> @panther2 what is your concern regarding the password generation for non website? It won't change, you will be able to use LessPass as today. You will just have a way to select the custom rule for stupid sites in one click.

Thank you for clarifying that. To me it sounded as if you intended to somehow simplify LessPass by reducing functionality. I am glad I misunderstood that. No more concerns fro my side, then.

**Comment by kidburglar** [comment]
Hello, thanks @guillaumevincent  to take time to write the blog post.

> I’m going to update LessPass web extension, mobile application and web component to send anonymous data to LessPass server. Restricted to the base domain name, site and the options used to generate a password. You will have the possibility to opt out. I will create and update existing policies.

I'm not a big fan about data sending, but there is an option to desactivate it so why not.

> Auto completion for the site field. Imagine with enough data, we will be able to propose auto completion in the site field. Mobile app and web extension will work the same.

Why not, but how will be the list updated ? If it work as the existing ad blockers it would mean that there will be public list and the possibiity to override theses list with personal one ?

At end, I think that what is happening is make the content of Lesspass Database (profiles options...) available locally ? Let me know if I'm wrong.

Cheers.

**Comment by guillaumevincent** [comment]
Probably like in ad blockers, a public repository on GitHub with base domain name and the profile. Maybe I'm wrong but a locally database will be huge. We'll see

**Comment by kidburglar** [comment]
Same if the database is huge I think it would be better that using the network for each use of Lesspass.

Also, if they are not locally it would prevent to use the feature if we are offline or if the repository is not reachable.

**Comment by kidburglar** [comment]
Hello @guillaumevincent 

Sorry to bump an closed issue, but what does happen exactly with the profiles idea ?
It's now implemented ?

Cheers.

**Comment by guillaumevincent** [comment]
@kidburglar the feedback wasn't good, so to be honest I stopped what I was doing and continue to clean the code. I'm still working on migrating the web component into a React app.

So nothing done actually regarding this feature. I'm not completely sure I will do it as described in the blog post.
