### ISSUE TITLE
some links are dead on the website

### ISSUE THREAD

**Issue by timaschew** [lesspass/lesspass#459]
1. https://github.com/lesspass/lesspass/#self-host-your-lesspass-database
2. https://github.com/lesspass/cli#install
3. https://github.com/lesspass/cozy#install

**Comment by edouard-lopez** [comment]
Thanks @timaschew for spotting the issues. 
Would you be able to submit a PR?

**Comment by guillaumevincent** [comment]
I'm currently rewriting the web site
So this will be fixed in september after my PTO
Thank you

**Comment by zcei** [comment]
@guillaumevincent is the rewrite `pacakges/lesspass-site` and has this actually been deployed to lesspass.com?

Wondering, because I stumbled across the dead CLI link as well and thought I'd submit a quick PR, but it looks fixed on current master, where the file in question was touched last Oct 19. So I'm a bit confused right now 😆 

https://github.com/lesspass/lesspass/blob/6bff48ac9b365bab2f0feae50fdbeb2c94a0b576/packages/lesspass-site/index.html#L417

**Comment by guillaumevincent** [comment]
I didn't update the frontend container on production no
I should do it

**Comment by guillaumevincent** [comment]
I updated the container on production
