### ISSUE TITLE
Different colors for numbers

### ISSUE THREAD

**Issue by JelleHissink** [lesspass/lesspass#490]
Other password managers use different colors for letters and numbers to differentate between 0 and O for instance.

**Comment by edouard-lopez** [comment]
We discussed characters ambiguity in #143 and switched to monospace font 

	font-family: Consolas,Menlo,Monaco,Courier New,monospace,sans-serif;

For instance, on my laptop I fallback to `monospace`, _i.e._ `Liberation Mono` where `0` and `O` are different:
![Screen Shot 2020-01-27 at 12 03 34](https://user-images.githubusercontent.com/1212392/73169822-36e37000-40fd-11ea-81c2-db321b5fc7f0.png)

However, I'm wondering why do you need this as it imply to reveal the generated password which is something, though possible, seldom needed (by design).

**Comment by guillaumevincent** [comment]
Maybe @JelleHissink you speak about the password field on mobile right ?
I will go with a better font than different colors for numbers because of ux issue with colors

**Comment by guillaumevincent** [comment]
before
![image](https://user-images.githubusercontent.com/943762/88412500-f6c62700-cdd9-11ea-87d8-e32f29a6e237.png)
after
![image](https://user-images.githubusercontent.com/943762/88412468-eb72fb80-cdd9-11ea-915b-ac07b7c14347.png)

**Comment by JelleHissink** [comment]
Sorry for the late response, hope I did not miss any of the fun.

I had some issues with reading the password. Sometimes I need to enter a password on a different device, e.g. a work related computer.
Then it is a burden to install the software as I already have it on my phone.
This looks like a workaround that is good enough, I suspect the 1 an l being more distinct like this too.

**Comment by guillaumevincent** [comment]
Yes you can try the font here https://sourcefoundry.org/hack/playground.html
