### ISSUE TITLE
question on master password safety

### ISSUE THREAD

**Issue by Sparkenstein** [lesspass/lesspass#518]
I simply loved the idea of stateless password manager, something I wanted for a long time now. Thanks for developing this tool.
But one thing I couldn't help noticing, If your master password is compromised somehow, then anyone can see anyone's password! How would you suggest mitigating this risk?

**Comment by pbaity** [comment]
@Sparkenstein you might be looking for this from the Lesspass wiki page ["Security model"](https://github.com/lesspass/lesspass/wiki/Security-model#what-is-the-risk-of-having-a-weak-master-password):

> This is why we recommend a master password of at least 20 characters, with letters, symbols, numbers. This is the only password you have to memorize, make it rock solid.

You're absolutely right that having a single master password creates a risk of getting all accounts compromised - so, simply put, you just make that single password as strong as you possibly can. In exchange, you only have to memorize one strong, unique password instead of dozens of them, and turning that single password into unique ones for each site is handled by Lesspass.

Hope this answers your question. A tip along with it: use a pass _phrase_, something long but memorable, with caps, symbols, and numbers thrown in. For example, `L3ssP@ss-P@SSw0rd-g3n3r@t0r`. Easy to remember, but hard to guess and hard to crack.

**Comment by guillaumevincent** [comment]
Hello,
You can see also what-is-the-risk-of-having-a-weak-master-password in the wiki https://github.com/lesspass/lesspass/wiki/Security-model#what-is-the-risk-of-having-a-weak-master-password
Fill free to reopen, if this doesn't answer your question
