### ISSUE TITLE
Simplify the Chrome and Firefox Extentions

### ISSUE THREAD

**Issue by anandubajith** [lesspass/lesspass#52]
Currently the Extenstions shows the password generation field where you have to manually enter the sitename, username and master password.
Can't we simplify this by using data from the current tab or having a handy keyboard shortcut to fill in the password when we have the username field filled?

**Comment by guillaumevincent** [comment]
@anandubajith have you use the extension ?

There is a shortcut to open the extension (There is a [bug for Firefox](https://github.com/lesspass/lesspass/issues/23), will be solve soon).
And the extension auto fill the site input.

I close because it's already there.

**Comment by anandubajith** [comment]
It would be nice to have this functionality.
If you go to a site and type the username.
You could just hit a handy keyboard shortcut which prompts you for your master password and autofills the generated password. 
Rather than having to click the extenstion and fill in the login .


Keep up the good work :+1:

**Comment by guillaumevincent** [comment]
We remove autofills generated password because :

 * autofills generated password came with breaches (see last [LastPass breach](https://labs.detectify.com/2016/07/27/how-i-made-lastpass-give-me-all-your-passwords/)) 
 * web extension load LessPass script on every site even if you don't open the extension. We don't want that. 

So we remove the functionnality

**Comment by anandubajith** [comment]
Okay . :+1:
