### ISSUE TITLE
The blog explains there both is no database, but also that there is a database... O_o

### ISSUE THREAD

**Issue by Pomax** [lesspass/lesspass#524]
Reading through https://blog.lesspass.com/lesspass-how-it-works-dde742dd18a4 I'm a bit confused by the combination of these two statements:

- "It does not save your passwords in a database"
- "You can host your own LessPass Database if you do not want to use the official one. "

Can someone clarify (ideally in the post) whether there is or isn't any database, and if there is one, what it contains and what it's used for?

**Comment by guillaumevincent** [comment]
In the blog post:

--


# What about complex password rules?

Sometimes sites have specific password rules. For instance, some banks only accept passwords made of numbers. So you have to remember both a strong password and complex rules.

Well, we built a “connected” version to tackle that. It works by saving your password’s profile, i.e. everything –except the master password and the generated password– to be able to generate the password. Then, next time you need this password you just have to select the profile and type the master password.

--

So there is no database, only math.
But because of dumb password rules, for certain sites you may need to save site's rules to generate the proper password.

But I agree, this one is confusing;

**Comment by Pomax** [comment]
Might be worth editing that a tiny bit (if that's possible?) to say:

> Well, we built a “connected” version to tackle that. It works by having a simple database that we use to save your password’s profile, i.e. everything –except the master password and the generated password– to be able to generate the password.

Just so that searching the page for the word `database` lets you find what it's actually used for?

**Comment by edouard-lopez** [comment]
Using the database is not something we want to push forward but a necessity due to some website bad-practices.

**Comment by Pomax** [comment]
Which is fine, but right now that blog post is effectively an official document that explains what lesspass is, and it doesn't adequately explain what the database is even for, and that should get a little edit to either remove all mention of it, or explain what it's used for, because mystery databases do not inspire trust =)

**Comment by guillaumevincent** [comment]
@Pomax I agree, do you have some time to improve those 2 paragraphs? I will be happy to update the blog post.

If not, no worries, I will try to fix this issue when I found some time.
Thanks

**Comment by Pomax** [comment]
I can file a PR, but I know nothing about the details of that database beyond what you explained, so if the text I suggested is good enough I can file a PR, but it's probably even faster for a repo-member to hit "edit" on the file and either commit that change directly or commit it as separate branch with immediate "create pull request" so they can insta-land it =)
