### ISSUE TITLE
Thoughts on LessPass and security

### ISSUE THREAD

**Issue by lsrom** [lesspass/lesspass#54]
Thanks for great tool for password managing. I actually wrote something like this for myself without knowing about you but maybe I'll switch to your solution instead of mine :+1: 

I wrote a short [blog post about LessPass and what should be done in near future](http://lsrom.cz/blog/2016/11/08/lesspass_why_holding_back_gets_you_nowhere.html). You can check it out [here](http://lsrom.cz/blog/2016/11/08/lesspass_why_holding_back_gets_you_nowhere.html) if you want but basically it says some security audit would be great before the app spread to millions of users...

Anyway, thanks and keep up the good work.

**Comment by guillaumevincent** [comment]
Thank you Isrom.

In term of security, here are the fields we should look at : 

-     STRENGTH: How well does it protect against increasingly creative attackers? How easy is it to get in?
-     TRUST: How much trust do you need to dish out? How many points of failure are there to this trust?
-     LOSS: How safe are you from locking yourself out? What happens when your hardware breaks or your house burns down?
-     USABILITY: How easy is it to use this product? How likely are you to bypass it for convenience?

Taken from here : http://masterpasswordapp.com/security.html

---

> But the algorithm used for generating password needs to be audited and checked before it goes viral.

I agree

> LessPass is definitely aware of need for security audit

Yes we are, and always will be. Your speech is this: 

- Never say LessPass is safe. 

- Clearly show the weaknesses of the tool. 

- Improve security and try not to reduce usability

**Comment by radum** [comment]
Another example that has some great example on how security can be improved is this one https://getvau.lt/

**Comment by edouard-lopez** [comment]
Please refer to #53 for conversation about security audit.

**Comment by guillaumevincent** [comment]
Thank you Isrom
I close to keep the repository clean
