### ISSUE TITLE
Save Default Options

### ISSUE THREAD

**Issue by abueide** [lesspass/lesspass#58]
Hey, it would be great if lesspass saved my last selected options, so if I want to use a password length of 16, it'll stay at 16 instead of 12 unless I change it back. That way I don't have to change the length to 16 every time I want to generate/get a password. The same should go for any other settings.

**Comment by edouard-lopez** [comment]
Thanks @abueide,

Are you aware of the [connected mode](https://github.com/lesspass/lesspass/wiki/How-does-it-work%3F#what-about-complex-password-rules)? One of its core feature is to let users **have custom options for every site**.

If you are talking about implementing this in the _private mode_, then there is some pros and cons:

### Pros

0. help **increase security** by letting user use stronger passwords ;

### Cons

0. **break the _ready-to-use_ idempotence** of the application (same password got computed everywhere) as users will have to set their options on every devices prior to using it ; 
0. "last selected options" will **create confusion and add to cognitive load** by requiring users to remember if they changed the options for a given site. In this scenario it's better to use the _connected mode_ ;
0. **create frustration** when users try several time to generate their password  and get it wrong because they forgot they change the default options.

The last argument is void _only_ if setting options is done prior to any use. Otherwise, it holds and

*  will force users to change their passwords to custom configuration, which is will be painful until we implemented #36 ; 
* rise the question about adding an onboarding mechanism to guide users to do that at an early stage (which does not totally prevent previous scenario).

### Conclusion

Better go for the _[connected mode](https://github.com/lesspass/lesspass/wiki/How-does-it-work%3F#what-about-complex-password-rules)_ for the time

**Comment by abueide** [comment]
@edouard-lopez I don't understand what cons if its simply an option to "remember settings per website". Like if I went to www.github.com and entered my info with a password length of 16 instead of 12, then I'd like it to remember that when I go to github, the password length is 16 so I don't have to change it each time. Maybe I have a password length of 14 on another website. It should remember the password length for both websites, as well as any other settings saved. I don't think this is a problem that requires a server to solve. The preferences should just be saved to disk.

**Comment by guillaumevincent** [comment]
@abueide if you want for site A to get length of 14 and site B length of site 16, you will need to store those informations somewhere : 

 - in your head
 - on client side (LocalStorage)
 - on server side (LessPass Database -> connected version)

We will start by developing the feature on server side because it will help us to solve those two https://github.com/lesspass/lesspass/issues/38 https://github.com/lesspass/lesspass/issues/56 in the future.

But sure we will allow users to save default options.

**Comment by abueide** [comment]
@guillaumevincent yeah I think that answers my question. So your saying theres no way to do that without connected? Just saving the profiles in LocalStorage without a server?

**Comment by guillaumevincent** [comment]
@abueide In the future If you as a community want this feature, we as a community will implement it. 

If I understand well, there is two features ?

 * save password profiles on localStorage
 * get default password options on localStorage 

So we will develop default password options on LessPass connected version. And then if the community want it, implement it on client side.

Am I right ? If so I will close this issue and reopen two issues, to clean this.

**Comment by abueide** [comment]
@guillaumevincent Yes, you are correct. Thanks :)

**Comment by sg-s** [comment]
> In the future If you as a community want this feature, we as a community will implement it.

i for one would love to have lesspass (the non-connected version) remember password lengths.

**Comment by guillaumevincent** [comment]
@sg-s @abueide  do not hesitate to add a :+1: on https://github.com/lesspass/lesspass/issues/72 or https://github.com/lesspass/lesspass/issues/70
