### ISSUE TITLE
Replace "tHis is a g00d! password"

### ISSUE THREAD

**Issue by fulldecent** [lesspass/lesspass#601]
Code makes reference to "tHis is a g00d! password"

This reference should be replaced with:

"D649CA4B-E925-4CC0-A5B7-F8C80BB8B996"

and then following that it should be noted as a code comment

`<-- this is a good password`

---

Also, please update https://github.com/lesspass/lesspass/wiki/Password-Generation-Specification

**Comment by guillaumevincent** [comment]
What do you mean ?

A master password like `D649CA4B-E925-4CC0-A5B7-F8C80BB8B996` is impossible to memorize

**Comment by fulldecent** [comment]
Got it, I see "Remember one master password" is a main selling point on this project at https://github.com/lesspass/lesspass/blob/master/README.md

Any password that is memorable will probably not be compliant with NIST Special Publication 800-132.

So the definition of a "good" password in this project is exceedingly less than industry standards.

Therefore this issue is without merit. Sorry about that, closing.

**Comment by guillaumevincent** [comment]
I think it's 800-63-3 now https://pages.nist.gov/800-63-3/sp800-63-3.html 
800-132 is pretty old

> Any password that is memorable will probably not be compliant with NIST Special Publication 800-132.

Did you read the document ? 

Because even 800-132 consider passphrase over 20 characters as strong enough;

There is also some research in the user experience field. Making a master password impossible to memorize is probably not a good idea.

Maybe I'm wrong, tell me if you read something I missed
