### ISSUE TITLE
Cant login to lesspass via Firefox Plugin

### ISSUE THREAD

**Issue by edurran** [lesspass/lesspass#634]
I can login to my account on the Web Version, but not with the Firefox Plugin.
Any suggestions?  
(I deleted my username for security. But you can see beside the password, that the icons say it's valid)
Thank you

**Comment by guillaumevincent** [comment]
may it be related to https://github.com/lesspass/lesspass/issues/613 ?

**Comment by Enderdead** [comment]
I have the same trouble with my instance since the last firefox extension update. 
The firefox plugin raises an `Oops! Something went wrong. Retry in a few minutes.`.

On the other side, my server raise an `backend_1   | Unauthorized: /api/auth/jwt/refresh/`.

I notice that your host domain schema has been updated.
Old version : 
```https://lesspass.com```
New version:
```https://api.lesspass.com```

Do we need to change the backend entry point from `https://domain.com/api` to `https://subdomain.com/` ?

Thank's for keeping doing great work !

**Comment by guillaumevincent** [comment]
you can do this yes, or you can update the backend container to use the latest version

**Comment by guillaumevincent** [comment]
Closing this
Probably related to #613
