### ISSUE TITLE
rolling password expiration

### ISSUE THREAD

**Issue by akhepcat** [lesspass/lesspass#65]
the counter field is an _interesting_ way to deal with password expiration/changes, however it becomes cumbersome when dealing with multiple passwords that all have different expiration policies.

An enhancement is therefore requested:
   each password ruleset may have an optional expiration timeframe (stored in seconds, for easier math, but expressed as human times)  such that after every 'X' timeframes past 'create', the counter is automatically incremented for that password only.

This method would ensure that you can always retrieve the prior generated password during password changes, but you will always be shown the 'current' password, according to the policy required by the specific ruleset.

The additional bonus is that you don't have to keep separate track of which passwords are at what counter increment - for automatically rotated passwords, that is.

**Comment by abueide** [comment]
I'm willing to take this on, but I'm kind of struggling because I have little javascript knowledge, coming from java.

@guillaumevincent why is there a core/index.js and a core/lib/index.js? Whats the purpose of each file?

Here's some pseudo code in java

```
dayOfYear = 1-366 depending on what day in the year it is (366 for last day of leap year)
expirationCycle = user input of how often they want their password to expire (in days for this example, but it can be more precise if a different unit is chosen such as seconds, minutes, or hours instead of days)

//This function will return a unique counter number depending on the date, and expirationTime
/* Use integers instead of decimals, because we don't care about a remainder, we only want to change the counter when a full time has occured. This will cause the last expiration rotation to be expirationTime + 365 (or 366 if leap year) % expirationTime. */

public int getExpirationCounter(int currentYear, int dayOfYear, int expirationCycle){ 
        return Integer.parseInt(new String(currentYear + dayOfYear / expirationCycle));  //This appends the amount of expiration cycles passed to the current year in order to create a unique counter number.
}
```
Some important things to note:

1) This feature should be an opt-in one, off by default.
2) There should be a default/recommended expiration cycle length to reduce the amount of information required to remember in order to regenerate a password.
3) Consider restricting expiration cycles to months, so you can append a month which is in an expiration cycle to the password making it easier to regenerate an old password if you remember the first 3 characters of the password (jan, feb, mar, etc.)
4) The counter is dependant on expiration cycles from january 1st, not the creation date. This is to make it so you don't have to remember the creation date to generate passwords.
5) Because of 4, there is a possibility of generating a password on the last day of the cycle which will change the password the next day. There should be some sort of check to only use a cycle's password if you are not more than 1/2 (just an example number) of the way through the current cycle, otherwise give the password of the next cycle.
6) There is a possibility of having a cycle that is nearly twice as long as a regular cycle, because of an incomplete cycle at the end of the year uses the same password as the previous cycle. There should be a check similar to the one described in 5 for this situation.

**Comment by guillaumevincent** [comment]
@abueide `core/index.js` is the source code in ES6 and `core/lib/index.js` is the ES5 equivalent after build.

Rolling password expiration always came with a persistance (localStorage or backend).
So this feature will be not be in `lesspass-core`. It will be in `lesspass-pure` or on the `backend`.

BTW we try to reduce the need of some storage/sync. This feature force the user to save some kind of informations somewhere. We're trying to make other features that go in that direction first.

**Comment by edouard-lopez** [comment]
@akhepcat Thanks, the use case is pretty interesting, and @guillaumevincent it helps highlight the emergence of the need for _connected mode_-only feature.

**Comment by abueide** [comment]
@guillaumevincent I disagree, if you use the default values, then you won't have to remember, unless you deviate from the default options, which is similar to every other setting anyway.

**Comment by guillaumevincent** [comment]
@abueide default options come with storage, so connected version or local storage.

**Comment by guillaumevincent** [comment]
Hello,
after some discussion with @edouard-lopez, this feature is out of scope.

We are not going in this way because password expiration is considered as a bad practice.
See [Digital Identity Guidelines Authentication and Lifecycle Management](https://pages.nist.gov/800-63-3/sp800-63b.html#memorized-secret-verifiers) by _NIST_ (US National Institute of Standards and Technology):

> Verifiers SHOULD NOT impose other composition rules (e.g., mixtures of different character types) on memorized secrets. Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically) and SHOULD only require a change if the subscriber requests a change or there is evidence of compromise of the authenticator.

I close this one
