### ISSUE TITLE
Is it possible to run this with Apache?

### ISSUE THREAD

**Issue by JacobDB** [lesspass/lesspass#67]
I've got my server set up for Apache currently, with a few subdomains. I believe because of this I can't use port 443, and that makes it weird to access the site (lesspass.example.com:444 instead of lesspass.example.com).

**Comment by guillaumevincent** [comment]
Port 443 is default port fort https.
You can't run two services on the same port. So if you run apache for your server and it already use port 443, then you will need to choose which service is listening. 

By default LessPass listen on port 443 and port 80. Redirect http to https.
If you change [this line](https://github.com/lesspass/lesspass/blob/master/docker-compose.prod.yml#L37) in your docker-compose file from `443:443` to `444:443` maybe it will works.

**Comment by slintes** [comment]
just in case somebody comes across this issue: I just installed lesspass behind HAProxy, which also does SSL termination, but for Apache it should work similar:

- remove the nginx service from the docker-compose file
- configure a Apache virtual host for the subdomain you want to use
- proxy requests to `/admin` and `/api` to the `backend` container (port 8000)
- proxy everything else to the `frontend` container (port 8080)

for HAProxy it looks like this:

```
frontend https
    ...
    acl web-lesspass hdr_end(host) -i lesspass.example.com
    acl web-lesspass-be path_beg /api /admin

    use_backend lesspass-be if web-lesspass web-pwd-be
    use_backend lesspass-fe if web-lesspass
```

```
backend pwd-be
    server lesspass-be lesspass_backend_1:8000

backend pwd-fe
    server lesspass-fe lesspass_frontend_1:8080
```

note: I'm running HAProxy with docker, too. In order to be able to use the `lesspass_backend_1` and `lesspass_frontend_1` links, you need to link them in the docker run command, and you need to run all lesspass services with `network_mode: "bridge"`

**Comment by JacobDB** [comment]
@slintes thanks for that, when I get few spare minutes I'll try and set this up again :)

**Comment by guillaumevincent** [comment]
@slintes Feel free to add a wiki page with this if you want. Thanks

**Comment by slintes** [comment]
good idea, will put that on my todo list for this week

**Comment by slintes** [comment]
done: https://github.com/lesspass/lesspass/wiki/Running-lesspass-behind-your-own-proxy

**Comment by edouard-lopez** [comment]
@slintes Thanks, I skimmed the text and improved formatting.

**Comment by slintes** [comment]
ok, I fixed the link on the wiki main page (title was changed and so the link) ;)
