### ISSUE TITLE
Differences to MasterPassword

### ISSUE THREAD

**Issue by xeruf** [lesspass/lesspass#670]
As someone considering to migrate to MasterPassword, what do you offer that could compel me to use your solution rather than MasterPassword/Spectre, in light of https://github.com/lesspass/lesspass/issues/526? 
Why did you not build upon the implementation of @lhunath rather than building a new application from scratch?

**Comment by guillaumevincent** [comment]
Algorithms are different. I don't remember exactly but in 2015/2016 MasterPassword App didn't use Script.

Password templates in MasterPassword App increase bruteforcability.

**Comment by xeruf** [comment]
Afaik MPW has used scrypt for a long time (mentioned e.g. here: https://www.wikiwand.com/en/Master_Password_(algorithm)#/Master_key_generation)

Doesn't lesspass also use password templates?

So only minor differences regarding the implemented algorithm?
Why not engage in a collaborative effort then rather than a new app?

**Comment by lhunath** [comment]
The scrypt KDF was added to Master Password in Feb, 2012, before the public release.

I don't want to speak for @guillaumevincent, but I think the core ideology is slightly different, where lesspass is more focused on providing a simple and light solution that just does its thing reliably and consistently & giving you the freedom and ability to make whatever changes to the output you'd like, while Master Password (referred to as [Spectre](https://spectre.app) from now on) is more focused on the practical reality of making this sustainable in the long run.

> Password templates in MasterPassword App increase bruteforcability.

A bold statement ;–)

We will of course each of us be the champions of our own implementation, and I believe it is healthy for there to exist alternatives in the market. A comparison of the security features should probably be done by an independent third party / researcher rather than by us.

A few points of deviation in approach/ideology I can tell:
- Spectre's KDF is memory-hard due to scrypt. This was done to make scaling of cracking cost-prohibitive (memory is more expensive than CPU).
- Spectre splits the KDF off from the password generation. Done to enable rapid generation of arbitrary passwords independent from the intentionally much slower key derivation step.
- Spectre doesn't allow you the freedom to pick and choose your own password template configuration. Done so you don't end up having to remember per-site special configurations.
- Spectre tries to make output passwords memorable / typeable while keeping entropy too high for sha/bcrypt cracking.
- Many of these things make Spectre more complicated internally.

**Comment by flexagoon** [comment]
The Spectre app looks much better in terms of UX, but it's iOS only

**Comment by lhunath** [comment]
The reason I didn't go into detail on that one is because the way you detail that out may end up being personal and biased, but I can give you my take, and then let you take away what seems valuable to you.  Perhaps someone with active experience using LessPass day-to-day can chime in with some counterpoints relevant to LessPass usage.

With that caveat, what I value sustainability wise in Spectre:
1. The cryptographic primitives underpinning the Spectre algorithm are more robust and will remain relevant longer. It is indeed a question whether CPU-hard KDFs such as PBKDF2 are still relevant in this age of ASICs and low-cost, low-power specialized computational cores.
2. The standard lesspass password policy is very often rejected by websites. If your aim is to generate passwords in a way that is 100% independent from reliance on secure storage, and at a scale of hundreds of sites/passwords, you really can't afford to have to remember site-specific password policy configurations.
3. Spectre doesn't limit itself to passwords, also generating security question answers, logins, even symmetric keys. Its relevance extends beyond just passwords.
4. Spectre allows integration in enterprise environments by syncing a role-specific user configuration across a team. Syncing your user configuration for personal use is also an option.

I personally feel that attempting to rely on lesspass exclusively in the long run would wind up with me hitting walls in each of these areas that would frustrate my ability to keep it pure, which would inevitably result in me having to combine lesspass with traditional password storage solutions such as browser storage, OS storage, a password vault app, and at that point I'd wonder what lesspass is still doing for me.

But again, I'd love to hear from some long-term LessPass users about their actual experiences.

**Comment by guillaumevincent** [comment]
Hey @lhunath !

> The scrypt KDF was added to Master Password in Feb, 2012, before the public release.

My memory sometimes makes me sad.

> referred to as Spectre from now

Good luck with Spectre, nice to see you are still working on your project!

> A bold statement ;–)

When I created LessPass I did the same. This assumption is not from me. It forces me to create the V2. See `the horror of LessPass` https://github.com/lesspass/lesspass/issues/88

> A comparison of the security features should probably be done by an independent third party / researcher rather than by us.

I agree. Sorry when I said "Password templates in MasterPassword App increase bruteforcability.". I didn't want to say: "LessPass is better". This is what I understood: The template of the password increase the bruteforcability. As said in the video.

And BTW SCrypt is better than pbkdf2 (algo used by LessPass). LessPass version 3 will use SCrypt. We discuss the implementation here: https://github.com/lesspass/lesspass/issues/389


> The cryptographic primitives underpinning the Spectre algorithm are more robust and will remain relevant longer. It is indeed a question whether CPU-hard KDFs such as PBKDF2 are still relevant in this age of ASICs and low-cost, low-power specialized computational cores.

True

> The standard lesspass password policy is very often rejected by websites due to silly website password policies. If your aim is to generate passwords in a way that is 100% independent from reliance on secure storage, and at a scale of hundreds of sites/passwords, you really can't afford to have to remember site-specific password policy configurations. This is an issue in Spectre too, but it is lessened by having a small set of standard policies to switch between.

Yes, I don't know if it's the same for you @lhunath but this is the problem that came a lot. I plan to try a POC to embed password policy in the core of LessPass.

@lhunath I don't know if you are interesting in video meeting together. I will be happy to share with you what I've discover running LessPass for 5 years now.

**Comment by lhunath** [comment]
Hey @guillaumevincent - you can connect with me at lhunath@lyndir.com. Wishing you all the best with your v2 as well!
