### ISSUE TITLE
[IDEA] Standalone HTML version for OFFLINE use

### ISSUE THREAD

**Issue by erreip** [lesspass/lesspass#68]
Is there a way to have this as a standalone HTML package that I can use OFFLINE?

Please advise.

Cheers

**Comment by guillaumevincent** [comment]
Right click -> Save Page As would do the trick
You probably will loose the icons but password generation will works

**Comment by monperrus** [comment]
FYI lesspass-pure is not standalone as a local file in firefox anymore, because loading `lesspass.min.js` on a `file:///*` URL is blocked by content blocking.

To make it standalone again as a local file, the JS code must be embedded in the HTML directly, as done for instance on `https://iancoleman.io/bip39/`
