### ISSUE TITLE
Database encryption proposition

### ISSUE THREAD

**Issue by Nedeas** [lesspass/lesspass#754]
Hi,

Thanks for your work.

We have thinking (with @cristianemenna) about a database encryption solution for Lesspass server and we would like your opinion about it.

We have seen that you're using PostgreSQL, and we love this database 🤩. There is an extension named [PGcrypto](https://www.postgresql.org/docs/9.5/pgcrypto.html) which allows us to use many functions for data encryption.

Our idea is :

- Add a field on user table in order to stock a key for crypt and encrypt current user data
- This key are cyphered with current user master password (this method allow changing master password without updating all crypted data for this user)
- Change Django backend for manipulate this key
- Develop cryptographic logic directly on PostgreSQL

With this methodology we will be able to restraint data access to its owner exclusively. Which means that if an account is ever compromised, the attacker would only have access to the data of the hacked user. We plan to use AES256 for encryption, this will ensure a high security level (provided that users use a strong and unique password).

In a second time, we imagine to being able to ask a specific master password for the key decryption. It would be requested to the user after authentication and by email (as for an OTP). We would like to have a functional version first using the user master password, before working on this improved final version.

So, we'd like to know if you're interested in this idea. We'd like to working on (both of us with @cristianemenna) and to propose you a PR if you agree. 

Thank you again!

**Comment by guillaumevincent** [comment]
Hello,

The server must not have any private key or equivalent on clear because that breaks end to end encryption. Can pgcrypto let us implement end to end encryption? Saving list of encrypted strings doesn't require anything else than PG.

The main idea has already been discussed [here](https://github.com/lesspass/lesspass/issues/185)

The main difficulty is to implement the workflow on the client side. I don't want to say no, and I don't want to let you work on a PR I can't review quickly.

And also I planned a migration of the frontend from vuejs to React. So I may someday take your code and migrate everything into React.

There is already a PR #597 that started the work, you may want to look at it before deciding to start your own.

Thank you for your proposition

**Comment by Nedeas** [comment]
Hello!

If your goal is to develop an E2EE solution, our proposition is not adapted indeed. We've been thinking exclusively about the database encryption in order to secure data in Lesspass server.

We understand that you don't have much time to spend on the project right now. Moreover, if you're thinking about a front-end migration soon, this may be not the best time to working on it.

Thank you anyway!
