### ISSUE TITLE
Clarify core functions - what is in hex?

### ISSUE THREAD

**Issue by tgulacsi** [lesspass/lesspass#82]
I'm trying to port the core functions to Go: https://github.com/tgulacsi/lesspass
What has to be in hex, and what shall be left as given?
In Go it is easy, we have []byte for arbitrary bytes, and string for utf8-encoded strings.

It seems to me the everything is in hex, but that means the 12 default length is only 6*8=48 bits!

My other problem is that if every hash is in hex, then _string2charCodes returns values 0..15, so we wont see "TVWXZ" chars if charType is C, for example!

**Comment by guillaumevincent** [comment]
> My other problem is that if every hash is in hex, then _string2charCodes returns values 0..15, so we wont see "TVWXZ" chars if charType is C, for example!

It's more complex than just last 4 letters, because it's a modulo of the char code. But you probably found a bug here, 4 uppercase letters are never in the password. I will open an issue for this one.

> It seems to me the everything is in hex, but that means the 12 default length is only 6*8=48 bits!

I don't understand this one. The default length is just a substring of the generated password after every transformations.

**Comment by tgulacsi** [comment]
My main problem is that why hex is used? I don't know JavaScript, so maybe it's forced, but this step reduces the possible passwords by a great amount.

The default length is 12, but here it is just 12 hex chars, which is only 6 bytes!


How is this (advance underlying algorithm) managed? I mean how can you ensure that the old passwords are generated when that's needed? Store some version number with the other params?

**Comment by guillaumevincent** [comment]
I choose hex because it was easy to manipulate than utf8-encoded strings.

> The default length is 12, but here it is just 12 hex chars, which is only 6 bytes!

> How is this (advance underlying algorithm) managed? I mean how can you ensure that the old passwords are generated when that's needed? Store some version number with the other params?



`masterPassword` and `login` are encrypted and transformed into a hex string (`a2eb5c29d8566a2eb5c29d8566...`). We take the 12 firsts chars. Default password template is `vcVCns`.

So we iterate over `a2eb5c29d856` char after char, look at the char type in the password template and the char code.

first letter : a -> charCode 97
char type : index of a in hash (0) in password template = vowel v
convert charCode 97 (a) into a vowel.

And so on until the last char.

Does it helps to understand the algorithm ?

**Comment by tgulacsi** [comment]
Yes, thank you!


Guillaume Vincent <notifications@github.com> ezt írta (időpont: 2016. nov.
15., K, 11:30):

**Comment by guillaumevincent** [comment]
Ok thaks. I close. 
Feel free to post on this thread to ask for extra help.
