### ISSUE TITLE
LessPass core algorithm v2

### ISSUE THREAD

**Issue by guillaumevincent** [lesspass/lesspass#89]
Thanks to #88 we are working on the version 2 of LessPass core.

**calcEntropy()**
`salt` = `site` + `login` + `counter`
`hash` = pbkdf2(`masterPassword`, `salt`) sha256, 64 bytes length, 100000 iterations
`entropy` = convert our 64 bytes hex `hash` into a number
 
**getSetOfCharacters()**
For every options we concatenate the corresponding subset of characters in order.

lowercase = `abcdefghijklmnopqrstuvwxyz`
uppercase = `ABCDEFGHIJKLMNOPQRSTUVWXYZ`
digits = `0123456789`
symbols = ``!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~``

For instance, for lowercase and uppercase letters the pool is:
 
     abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ

**renderPassword()**
For the first character of the generated password, we do a long division between entropy and the length of the set of characters (`52` per above example). Then, we use the remainder as an index to pick the first char of the generated password in the set of characters.
Then we repeat by using the quotient as the new entropy's value.
We do that until we reach the expected length of the generated password minus number of rules.

**addOneCharPerRule()**
To match the specific rule ("your password should contains at least one number and one special char") we ensure generated password contains at least one letter per rule is present. We insert one char per rule in the generated password from first consumeEntropy.

**default options**
pbkdf2 iterations: 100 000
password length: 16
default options: lowercase + uppercase + digits + symbols

lowercase length: 26 (alphabet)
uppercase length: 26 (alphabet)
digits length: 10
symbols length: 32

Steve Gibson talk about 33 specials chars ? Does he count ` ` (space) as a special char ? Or I miss one ?

Is this a good transcript of the video ?

**Comment by guillaumevincent** [comment]
The first implementation of the core v2: 
https://github.com/lesspass/core/blob/master/src/v2.js

Tests:
https://github.com/lesspass/core/tree/master/tests/v2

**Comment by ewjmulder** [comment]
Hi Guillaume, I was just about to start using LessPass when I encountered this. I agree with Steve Gibson that the algorithm v1 is not ok. But I also agree with you that you can't get everything right the first time. And it is good that LessPass is fully open source, so these issues can be publicly discussed and fixed. A downside of the LessPass model is that the passwords are tied to the algorithm used, so once released you can never change it again, only add new versions. But I guess that is just the way it is with this model.

As for the algorithm v2: I think your description above is a good summary of the contents of the video. You are right about the special characters, see: https://en.wikipedia.org/wiki/List_of_Unicode_characters#Basic_Latin -> "The 33 characters classified as ASCII Punctuation & Symbols are also sometimes referred to as ASCII special characters" and include the space. But maybe you should leave out the space, as it might cause problems for some sites that do not allow spaces or do not count them as a 'special character'.

As for the default options: I think the special characters should be included, since many sites require them to be included in your password. In my opinion every extra action needed to be able to restore your password (like clicking the 'special characters' checkbox) will make LessPass less usable, so I think you should focus on a broadly usable default setting.

On that topic I have another thought: when you would implement algorithm v2 the way described above, so with full character set and fully randomized, there is no guarantee that you meet the password criteria like a minimum of one lower case / upper case / number case / special character (I have never before heard of the criteria 'no two consecutive vowels'). So as default setting I think the generated password should always include one of each of the 4 groups of characters (lower, upper, number, special). I think this will satisfy the password policy of most websites. For more complex ones, you can still use the 'connected' feature.

Some thoughts on the way you could guarantee this, without giving up too much entropy:
1. Have a fully random password according to the algorithm v2 specs of length 12
2. Generate 1 character from the 4 groups in the same random way
3. Insert these 4 characters at pseudo-random places in the password from step 1. The index to insert can be generated in the same way as picking a letter from an alphabet, only now you use the (current) size of the password and the outcoming number as index. (in v1 you do not start with a number, but I have never heard about this as a password policy, so I guess you can skip that or at the end include a step to in case of a first non-letter swap it with the first letter in the generated password)

Good luck with implementing v2 (I see you just added a first implementation while I was typing this ;)

**Comment by guillaumevincent** [comment]
@ewjmulder thank you :)
Yes I have build a first version, it is not yet finished.

What I don't know:
 * What is the length that works for as many sites as possible (12 works well, but less secure than 14)
 * If there is more sites that ask special characters than sites which refuse special characters.

Concerning your thought, and to go even further, **we must ensure that at least one letter per subset is present.** Is this feature correct?

**Comment by ewjmulder** [comment]
Hmm, yes, it depends on what your goal is with the the default settings:
A. Cover as many websites as possible without being too insecure
B. Be as secure as possible without ruling out too many websites

I would opt for option B for 2 reasons:
- It's better to be known as a secure password 'manager' where you sometimes have to turn down the defaults a bit on websites lacking proper password acceptance.
- It is to be expected that websites will be evolving towards accepting stronger passwords (= longer & with all characters) in the future and/or tightening their password policy rather than the other way around. So setting the bar a little higher now ensures the settings stay relevant in the future.

Regarding your re-phrasing: _"Concerning your thought, and to go even further, we must ensure that at least one letter per subset is present. Is this feature correct?"_
Yes, indeed, I think that should be the case. It only weakens the password a little bit, but ensures compatibility with a website's password policy where otherwise LessPass would become unusable if you are unlucky and get only letters but need a number as well. I guess this is what other password managers do as well when asked to generate passwords with certain characteristics.

Coincidentally, I visited a talk from security expert Jim Manico (https://www.linkedin.com/in/jmanico) about this subject this week and he's also a strong advocate of long random passwords with many different characters and was bashing websites that do not accept those yet. His own systems accept passwords with all characters with a size of up to 4000! (only limiting the size to prevent DDOS attacks with huge passwords)

Either way, reality forces us to deal with websites that cannot handle very secure default settings. One way to deal with that might be to have 2 or 3 different 'default' settings. For instance: safety 'low' has only alpha numeric of length 8, safety 'medium' has alpha numeric of size 16 and safety 'high' has alpha numeric + specials of length 24. Maybe aided with colors red, yellow, green from a UX point of view. This also triggers users to be feeling uneasy about using a 'red' password for a certain website, because that website cannot handle a 'green' password and maybe they will contact the website to ask for 'green' password compatibility. If I let my thoughts run freely you could even imagine websites having a 'LessPass green password compatible' kind of logo on the login page.

This system could further be aided by a centralized knowledge base (KB) containing website URL's and red/yellow/green labels that indicate their compatibility and the LessPass website, browser plugins and apps querying that KB to pre-select the right colored default setting to help the user.

Maybe I'm making it too big/complex now, but I think it's worth considering, since there seems to be no single 'default fits all' option available.

**Comment by guillaumevincent** [comment]
@ewjmulder I will set default password with specials char too and default length password equals to 16.
We can also add an option to remove the "at least one letter per subset is present".

**Comment by ewjmulder** [comment]
@guillaumevincent Ok, that sounds like a pretty strong default that most websites should accept. But why an option to disable "at least one letter per subset is present"? With length 16 there should be enough entropy for enforcing that rule. If you don't want a certain character group in your password, you can unselect that group but why would you want a chance to probably have some characters in your password, but maybe not? (other than the entropy argument)

**Comment by guillaumevincent** [comment]
It was an idea to get the max entropy we can. But you probably right.

**Comment by guillaumevincent** [comment]
@ewjmulder By default the generated password always include one char per rule (lower, upper, number, special)

https://github.com/lesspass/core/blob/master/src/v2.js

If you have 5 minutes to look at the code, and tell me if the implementation corresponds to the algorithm that you described above.

Thank you

**Comment by ewjmulder** [comment]
@guillaumevincent See my code review in this PR: https://github.com/lesspass/core/pull/3

**Comment by davidbear** [comment]
@guillaumevincent I'm concerned with your set of special characters. Many sites forbid &@='"%. in fear of some yet to be determined hack. It might be useful to have a set of "web safe" special characters.

**Comment by guillaumevincent** [comment]
@davidbear we already use `@&%?,=[]_:-+*$#!\'^~;()/.` in the previous version. @ewjmulder got an idea of green labels that indicate web site compatibility with LessPass password.
I like this idea.
Maybe it will force website to implement authentication correctly.

"We safe" can be reach with special char unchecked no ?

**Comment by davidbear** [comment]
@guillaumevincent , Yes it can, but it then lacks all of those 18 extra web safe characters. I understand that you have bigger fish to fry at this point.

**Comment by guillaumevincent** [comment]
@davidbear nop we will take the time we need to make our best :)
Can you give me your 18 "web safe" symbols? I will do some tests and see if we reduce this number.

**Comment by davidbear** [comment]
@guillaumevincent Thanks    ?,[]_:-+$#!\^~;()/

**Comment by guillaumevincent** [comment]
@davidbear I did some tests today and I encountered two sites one refusing `:` and one refusing `/`
We probably need to do a wall of shame of bad sites

**Comment by guillaumevincent** [comment]
I close the new version is online

**Comment by ewjmulder** [comment]
Great work, I hope v2 will live long and prosper! ;-)
