### ISSUE TITLE
Build an electron app

### ISSUE THREAD

**Issue by zedtux** [lesspass/lesspass#90]
It should be easy and would be nice to have an [electron](http://electron.atom.io) app for lesspass.

**Comment by guillaumevincent** [comment]
@zedtux we already create an electron app: https://github.com/lesspass/desktop
I deprecated the project because we don't have a lot of time to maintain too many projects.
The number of download was also very low.

Will see if this issue get a lot of traction, maybe we will reopen the project.

**Comment by zedtux** [comment]
Merci Guillaume for your quick answer 👍

**Comment by rodolpheh** [comment]
Did the `desktop` repository disappeared ? I can't find any way to build the electron package anymore.

**Comment by guillaumevincent** [comment]
Yes I decided to remove the code. I don't have time to maintain the code.

**Comment by rodolpheh** [comment]
Is there any way to retrieve the latest commit from the `desktop` repository ? I maintain the `lesspass-desktop-git` and got complains recently that the package can't be built anymore because of the code removal.

In case I can get my hands on the `desktop` code, did the algorithm for generating password  has changed or is it only changes related to the client/server communication ? My next question being : would you consider it safe to maintain the outdated desktop application just for the sake of using the algorithm (this is actually the only way I use lesspass, I don't have an account for storing passwords on a server) ? The fact that it is outdated would be reflected in the package description and I would advise users not to use the login part (or in the best case, remove it from the code through a patch).

I hope I made myself understandable

**Comment by guillaumevincent** [comment]
Hello @rodolpheh 
sorry for this
you can find the old code in the git history
commit just before the cleanup: https://github.com/lesspass/lesspass/tree/495e8b3323cb3a7f24dce03e4d01158affa8ccf7/desktop
Feel free to fork the source code

**Comment by edouard-lopez** [comment]
@rodolpheh we have a [CLI package](https://github.com/lesspass/lesspass/tree/master/cli) written in Python that is up-to-date.

**Comment by rodolpheh** [comment]
Thank you everyone. I've updated the AUR package to reflect this. It is now indicated as deprecated and I recommend users to switch to the new lesspass-cli. I may take some time this week-end to produce a lesspass-cli package for the AUR.
